"use strict";
var $=id=>document.getElementById(id),canvas=$("canvas"),ctx=canvas.getContext("2d");
var mode="hero",COLS=27,WORLD_ROWS=75,START_ROW=69,grid=[],openCells=[];
var dirs={left:{x:-1,y:0},right:{x:1,y:0},up:{x:0,y:-1},down:{x:0,y:1}};
var player,ghosts=[],hazards=[],targets=[],followers=[],pathHistory=[],visitedDots=new Set(),journeyFlags={gate:false,road:false,pass:false,canaan:false};
var score=0,lives=3,power=0,powerUntil=0,invulnUntil=0,stage=0,running=false,loopStarted=false,lastTime=0,checkpoint={c:13,r:69},sandstormRow=76,sandstormActive=false;
var dpr=1,cw=1,ch=1,tile=1,visibleRows=16,cameraTop=0,firstSwipe=false,swipeId=null,sx=0,sy=0,swipeFired=false;
var musicOn=true,musicVol=.48,audio=null,master=null,filter=null,nextBeat=0,beat=0,musicTimer=null;
var verseWords=["For","all","have","sinned,","and","come","short","of","the","glory","of","God;"],verseKeys=verseWords.map(w=>w.toLowerCase().replace(/[^a-z]/g,"")),wordIndex=0,wordTargets=[],combo=0,verseGlitch=74;
var heroPickups=[{id:"sarai",name:"SARAI",kind:"person",c:5,r:65},{id:"lot",name:"LOT",kind:"person",c:21,r:63},{id:"house1",name:"HOUSEHOLD",kind:"group",c:9,r:59},{id:"house2",name:"HOUSEHOLD",kind:"group",c:19,r:57},{id:"goods",name:"GOODS",kind:"goods",c:3,r:53},{id:"tents",name:"TENTS",kind:"goods",c:23,r:51},{id:"camel",name:"CAMEL",kind:"camel",c:13,r:61},{id:"flock",name:"FLOCK",kind:"flock",c:15,r:55}];
var picked={};
function rnd(){return Math.random()}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function key(c,r){return c+","+r}function dist(a,b){return Math.hypot(a.c-b.c,a.r-b.r)}
function zoneFor(r){if(r>=48)return"HARAN";if(r>=39)return"CITY GATE / ROAD";if(r>=25)return"OPEN ROAD";if(r>=10)return"ROCKY PASS";return"CANAAN"}
function wall(c,r){c=Math.round(c);r=Math.round(r);if(r<0||c<0||r>=WORLD_ROWS||c>=COLS)return true;if(r===47&&!journeyFlags.gate&&c>=11&&c<=15)return true;return grid[r][c]==="#"}
function canAt(c,r,d){return !wall(Math.round(c)+d.x,Math.round(r)+d.y)}
function carve(c,r){if(r>0&&r<WORLD_ROWS-1&&c>0&&c<COLS-1)grid[r][c]=" "}
function buildHeroWorld(){grid=[];openCells=[];for(let r=0;r<WORLD_ROWS;r++)grid[r]=Array(COLS).fill("#");for(let r=1;r<WORLD_ROWS-1;r++){if(r%2===1){for(let c=1;c<COLS-1;c++)carve(c,r)}else{let picks=[3,7,13,19,23];if(r%6===0)picks=[5,11,15,21];if(r%10===0)picks.push(25);picks.forEach(c=>carve(c,r))}}for(let r=50;r<=70;r++)for(let c=2;c<=24;c++)if((r%6>=1&&r%6<=3)&&(c%8>=1&&c%8<=5))carve(c,r);for(let c=1;c<COLS-1;c++)grid[47][c]="#";for(let c=11;c<=15;c++)grid[47][c]=" ";carve(13,46);carve(13,45);for(let r=34;r<=45;r+=4)for(let c=2;c<=24;c++)carve(c,r);for(let r=34;r<=45;r++)for(let c=5;c<=7;c++)carve(c,r);for(let r=34;r<=45;r++)for(let c=19;c<=21;c++)carve(c,r);for(let r=10;r<=32;r++){let center=13+Math.round(Math.sin(r*.65)*6);for(let c=center-2;c<=center+2;c++)carve(c,r);if(r%5===0)for(let c=3;c<=23;c++)carve(c,r)}for(let r=2;r<=9;r++)for(let c=3;c<=23;c++)carve(c,r);heroPickups.forEach(p=>{carve(p.c,p.r);carve(p.c,p.r-1);carve(p.c,p.r+1)});carve(13,69);carve(13,68);for(let r=1;r<WORLD_ROWS-1;r++)for(let c=1;c<COLS-1;c++)if(grid[r][c]===" ")openCells.push({c,r})}
function buildVerseWorld(){grid=[];openCells=[];WORLD_ROWS=301;START_ROW=297;for(let r=0;r<WORLD_ROWS;r++)grid[r]=Array(COLS).fill("#");for(let r=1;r<WORLD_ROWS-1;r++){if(r%2===1){for(let c=1;c<COLS-1;c++)carve(c,r)}else{let picks=[];while(picks.length<5){let c=1+2*Math.floor(rnd()*12);if(!picks.includes(c))picks.push(c)}picks.forEach(c=>carve(c,r))}}for(let r=1;r<WORLD_ROWS-1;r++)for(let c=1;c<COLS-1;c++)if(grid[r][c]===" ")openCells.push({c,r})}
function resetPlayer(c,r){player={c:c||13,r:r||START_ROW,dir:{x:0,y:0},want:{x:0,y:0},lastCenter:"",mouth:0,lastDot:""};pathHistory=[];for(let i=0;i<800;i++)pathHistory.push({c:player.c,r:player.r})}
function randomOpenIn(minR,maxR){for(let i=0;i<200;i++){let r=Math.round(minR+rnd()*(maxR-minR)),c=1+Math.floor(rnd()*(COLS-2));if(!wall(c,r))return{c,r}}return{c:13,r:minR}}
function spawnHeroGhost(type,r){let p=randomOpenIn(Math.max(2,r-2),Math.min(WORLD_ROWS-2,r+2));ghosts.push({type,c:p.c,r:p.r,dir:{x:rnd()<.5?-1:1,y:0},lastCenter:"",speed:type==="chaser"?2.6:type==="ambush"?2.35:2.15,color:type==="chaser"?"#f05c5c":type==="ambush"?"#db73cf":"#6bc9da"})}
function setupHeroHazards(){hazards=[];hazards.push({type:"cart",c:3,r:67,v:3.2,min:2,max:24},{type:"cart",c:23,r:55,v:-2.7,min:2,max:24},{type:"cart",c:4,r:51,v:3,min:2,max:24});hazards.push({type:"dust",c:5,r:39,t:rnd()*6},{type:"dust",c:21,r:35,t:rnd()*6},{type:"dust",c:9,r:29,t:rnd()*6});hazards.push({type:"rock",c:13,r:22,t:0,armed:false},{type:"rock",c:8,r:17,t:1.4,armed:false},{type:"rock",c:18,r:13,t:2.8,armed:false})}
function initHero(){mode="hero";COLS=27;WORLD_ROWS=75;START_ROW=69;score=0;lives=3;power=0;powerUntil=0;invulnUntil=performance.now()+1800;stage=0;journeyFlags={gate:false,road:false,pass:false,canaan:false};sandstormRow=76;sandstormActive=false;checkpoint={c:13,r:69};picked={};followers=[];visitedDots=new Set();ghosts=[];targets=heroPickups.map(p=>Object.assign({},p));buildHeroWorld();resetPlayer(13,69);setupHeroHazards();spawnHeroGhost("patrol",62);spawnHeroGhost("ambush",58);spawnHeroGhost("chaser",52);updateHeroHud()}
function startStory(){$("storyKicker").textContent="GENESIS 12:1 KJV";$("storyTitle").textContent="THE CALL";$("storyVerse").textContent="Now the LORD had said unto Abram, Get thee out of thy country, and from thy kindred, and from thy father's house, unto a land that I will shew thee:";$("storyText").textContent="Haran is a real maze now. Find Sarai, Lot, the household and everything gathered for the journey. When the caravan is complete, the city gate will open.";$("storyGo").textContent="BEGIN IN HARAN";$("story").classList.add("show")}
function showCheckpoint(kicker,title,verse,text,button){running=false;$("storyKicker").textContent=kicker;$("storyTitle").textContent=title;$("storyVerse").textContent=verse;$("storyText").textContent=text;$("storyGo").textContent=button||"CONTINUE";$("story").classList.add("show")}
function countPicked(){return Object.keys(picked).length}
function updateHeroHud(){let count=countPicked(),z=zoneFor(player?player.r:69);$("zone").textContent=z;$("lives").textContent=lives;$("score").textContent=score;$("power").textContent=performance.now()<powerUntil?"ON":power+"/4";$("powerStat").style.display="";if(stage===0){$("objective").textContent="ASSEMBLE THE CARAVAN";$("missionText").textContent="GATHER SARAI, LOT, HOUSEHOLD & POSSESSIONS";$("missionCount").textContent=count+"/8";$("missionBarFill").style.width=count/8*100+"%"}else if(stage===1){$("objective").textContent="THE GATE IS OPEN — DEPART HARAN";$("missionText").textContent="LEAD THE WHOLE CARAVAN THROUGH THE CITY GATE";$("missionCount").textContent="GATE";$("missionBarFill").style.width="100%"}else{let pct=clamp((69-player.r)/62,0,1);$("objective").textContent=stage===2?"JOURNEY TOWARD CANAAN":stage===3?"SURVIVE THE ROCKY PASS":"ENTER CANAAN";$("missionText").textContent="KEEP MOVING — THE CARAVAN IS FOLLOWING";$("missionCount").textContent=Math.round(pct*100)+"%";$("missionBarFill").style.width=pct*100+"%"}}
var flashTimer;function flash(text,bad){clearTimeout(flashTimer);$("flash").textContent=text;$("flash").className="show "+(bad?"bad":"good");flashTimer=setTimeout(()=>$("flash").className="",720)}
function queueDir(name){if(!player||!dirs[name])return;let d=dirs[name];player.want={x:d.x,y:d.y};if(player.dir.x===-d.x&&player.dir.y===-d.y){player.dir={x:d.x,y:d.y};player.lastCenter=""}$("queue").textContent={left:"←",right:"→",up:"↑",down:"↓"}[name]}
function collectDot(){let c=Math.round(player.c),r=Math.round(player.r),k=key(c,r);if(player.lastDot===k)return;player.lastDot=k;if(!visitedDots.has(k)){visitedDots.add(k);score++;combo++;if(combo>0&&combo%64===0){score+=100;flash("64-DOT BONUS!",false)}}}
function pickupHero(i){let t=targets[i];picked[t.id]=true;targets.splice(i,1);followers.push({name:t.name,kind:t.kind,index:followers.length});score+=350;power++;sfx("correct");flash(t.name+" JOINED THE CARAVAN!",false);if(power>=4){power=0;powerUntil=performance.now()+7000;sfx("power");flash("CARAVAN POWER!",false)}if(countPicked()===8){stage=1;journeyFlags.gate=true;score+=1000;sfx("gate");flash("ALL READY — HARAN GATE OPEN!",false)}updateHeroHud()}
function pathSample(delay){let idx=Math.max(0,pathHistory.length-1-delay);return pathHistory[idx]||{c:player.c,r:player.r}}
function updateFollowers(){pathHistory.push({c:player.c,r:player.r});if(pathHistory.length>1000)pathHistory.shift()}
function stepPlayer(dt){let rc=Math.round(player.c),rr=Math.round(player.r),near=Math.abs(player.c-rc)<.13&&Math.abs(player.r-rr)<.13,k=key(rc,rr),stopped=!player.dir.x&&!player.dir.y;if(near&&(player.lastCenter!==k||stopped)){player.c=rc;player.r=rr;collectDot();if(canAt(rc,rr,player.want))player.dir={x:player.want.x,y:player.want.y};if(!canAt(rc,rr,player.dir))player.dir={x:0,y:0};player.lastCenter=k}let speed=5.35+(performance.now()<powerUntil?.55:0);player.c+=player.dir.x*speed*dt;player.r+=player.dir.y*speed*dt;player.mouth+=dt*14;updateFollowers()}
function ghostTarget(g){if(g.type==="ambush")return{c:player.c+player.dir.x*4,r:player.r+player.dir.y*4};if(g.type==="patrol")return{c:player.c,r:g.r};return player}
function chooseGhostDir(g,now){let opts=Object.values(dirs).filter(d=>canAt(g.c,g.r,d));if(!opts.length)return{x:0,y:0};let rev={x:-g.dir.x,y:-g.dir.y},nr=opts.filter(d=>!(d.x===rev.x&&d.y===rev.y));if(nr.length)opts=nr;let t=ghostTarget(g),scared=now<powerUntil;opts.sort((a,b)=>{let da=Math.abs(g.c+a.x-t.c)+Math.abs(g.r+a.y-t.r),db=Math.abs(g.c+b.x-t.c)+Math.abs(g.r+b.y-t.r);return scared?db-da:da-db});return rnd()<.82?opts[0]:opts[Math.floor(rnd()*opts.length)]}
function stepGhost(g,dt,now){let rc=Math.round(g.c),rr=Math.round(g.r),near=Math.abs(g.c-rc)<.13&&Math.abs(g.r-rr)<.13,k=key(rc,rr);if(near&&g.lastCenter!==k){g.c=rc;g.r=rr;g.dir=chooseGhostDir(g,now);g.lastCenter=k}let sp=g.speed*(now<powerUntil?.68:1);g.c+=g.dir.x*sp*dt;g.r+=g.dir.y*sp*dt}
function stepHazards(dt,now){hazards.forEach(h=>{if(h.type==="cart"){h.c+=h.v*dt;if(h.c<h.min||h.c>h.max){h.v*=-1;h.c=clamp(h.c,h.min,h.max)}}else if(h.type==="dust"){h.t+=dt;h.c=13+Math.sin(h.t*1.6+h.r)*9}else if(h.type==="rock"){h.t-=dt;if(h.t<=0&&!h.armed){h.armed=true;h.warn=1;h.c=clamp(Math.round(player.c),3,23)}if(h.armed){h.warn-=dt;if(h.warn<=0){h.fall=(h.fall||0)+dt*4.4;if(h.fall>3.2){h.armed=false;h.fall=0;h.t=2.2+rnd()*2.8}}}}})}
function hazardCollision(now){for(let h of hazards){if(h.type==="cart"&&player.r>48&&Math.hypot(player.c-h.c,player.r-h.r)<.55){hurt("CART COLLISION",now);return}if(h.type==="dust"&&player.r<46&&player.r>24&&Math.hypot(player.c-h.c,player.r-h.r)<.65){hurt("DUST DEVIL",now);return}if(h.type==="rock"&&player.r<25&&h.armed&&h.warn<=0&&h.fall>.8&&h.fall<2.1&&Math.abs(player.c-h.c)<.65&&Math.abs(player.r-h.r)<1.1){hurt("ROCKFALL",now);return}}}
function hurt(reason,now){if(now<invulnUntil)return;lives--;sfx("hit");flash(reason,true);combo=0;if(lives<=0){finishHero(false);return}resetPlayer(checkpoint.c,checkpoint.r);invulnUntil=now+1900;powerUntil=0;ghosts=[];if(stage<=1){spawnHeroGhost("patrol",Math.max(50,checkpoint.r-4));spawnHeroGhost("ambush",Math.max(50,checkpoint.r-8));spawnHeroGhost("chaser",Math.max(49,checkpoint.r-12))}else{spawnHeroGhost("chaser",Math.max(10,checkpoint.r-6));spawnHeroGhost("ambush",Math.max(10,checkpoint.r-10))}sandstormRow=Math.max(sandstormRow,player.r+10);updateHeroHud()}
function checkHeroProgress(now){for(let i=targets.length-1;i>=0;i--)if(dist(player,targets[i])<.52){pickupHero(i);break}for(let g of ghosts)if(dist(player,g)<.55){if(now<powerUntil){score+=200;g.r=Math.max(2,player.r-9);g.c=3+Math.floor(rnd()*20);g.lastCenter="";sfx("eat");flash("ARCADE GHOST CHOMP +200",false)}else hurt("ARCADE GHOST GOT YOU",now);break}hazardCollision(now);if(stage===1&&player.r<47){stage=2;checkpoint={c:13,r:43};sandstormActive=true;ghosts=[];spawnHeroGhost("chaser",42);spawnHeroGhost("ambush",38);score+=700;showCheckpoint("GENESIS 12:4 KJV","ABRAM DEPARTED","So Abram departed, as the LORD had spoken unto him; and Lot went with him: and Abram was seventy and five years old when he departed out of Haran.","The caravan is through the gate. Now the mission changes: the maze opens into the journey toward Canaan, with new terrain and new arcade hazards.","TAKE THE ROAD")}if(stage>=2&&!journeyFlags.road&&player.r<34){journeyFlags.road=true;checkpoint={c:13,r:35};score+=500;flash("OPEN ROAD CHECKPOINT!",false)}if(stage===2&&player.r<25){stage=3;journeyFlags.pass=true;checkpoint={c:13,r:27};ghosts=[];spawnHeroGhost("chaser",21);spawnHeroGhost("ambush",16);spawnHeroGhost("patrol",12);score+=700;showCheckpoint("GENESIS 12:5 KJV","THE WHOLE CARAVAN","And Abram took Sarai his wife, and Lot his brother's son, and all their substance that they had gathered, and the souls that they had gotten in Haran; and they went forth to go into the land of Canaan; and into the land of Canaan they came.","You brought the entire caravan out of Haran. One hard section remains: thread everyone through the rocky pass and reach the land of Canaan.","ENTER THE PASS")}if(stage===3&&player.r<10){stage=4;journeyFlags.canaan=true;checkpoint={c:13,r:11};score+=800;sandstormActive=false;ghosts=[];flash("CANAAN AHEAD!",false)}if(stage===4&&player.r<5)finishHero(true);if(sandstormActive&&player.r>sandstormRow-.5)hurt("THE SANDSTORM CAUGHT THE CARAVAN",now)}
function updateHero(dt,now){if(!running)return;stepPlayer(dt);ghosts.forEach(g=>stepGhost(g,dt,now));stepHazards(dt,now);if(sandstormActive)sandstormRow-=dt*(.85+(stage>=3?.35:0));checkHeroProgress(now);cameraTop=clamp(player.r-visibleRows*.68,0,WORLD_ROWS-visibleRows);updateHeroHud()}
function spawnVerseWords(){if(wordIndex>=verseKeys.length){wordTargets=[];return}let decoys=["some","many","people","always","were","unto","through","great","world","every","grace","shall"],pool=[verseKeys[wordIndex],...decoys.sort(()=>rnd()-.5).slice(0,4)];wordTargets=[];pool.sort(()=>rnd()-.5).forEach(w=>{let p=randomOpenIn(Math.max(1,player.r-9),Math.max(2,player.r-3));wordTargets.push({word:w,c:p.c,r:p.r})})}
function initVerse(){mode="verse";COLS=27;WORLD_ROWS=301;START_ROW=297;score=0;lives=3;power=0;powerUntil=0;wordIndex=0;combo=0;visitedDots=new Set();ghosts=[];wordTargets=[];verseGlitch=300;buildVerseWorld();resetPlayer(13,297);checkpoint={c:13,r:297};invulnUntil=performance.now()+1800;spawnHeroGhost("chaser",289);spawnHeroGhost("ambush",284);spawnHeroGhost("patrol",279);spawnVerseWords();$("ref").innerHTML='ROMANS 3:23 KJV <em>VERSE CHOMP</em>';$("zone").textContent="ENDLESS RUN";$("powerStat").style.display="";updateVerseHud()}
function updateVerseHud(){let done=verseWords.slice(0,wordIndex).join(" ");$("objective").innerHTML=(done?done+" ":"")+(wordIndex<verseWords.length?"______":"✓ VERSE COMPLETE");$("missionText").textContent="CHOMP THE NEXT KJV WORD";$("missionCount").textContent=wordIndex+"/"+verseWords.length;$("missionBarFill").style.width=wordIndex/verseWords.length*100+"%";$("lives").textContent=lives;$("score").textContent=score;$("power").textContent=performance.now()<powerUntil?"ON":power+"/4"}
function updateVerse(dt,now){if(!running)return;stepPlayer(dt);ghosts.forEach(g=>stepGhost(g,dt,now));for(let i=wordTargets.length-1;i>=0;i--)if(dist(player,wordTargets[i])<.5){let t=wordTargets[i];if(t.word===verseKeys[wordIndex]){score+=100;wordIndex++;power++;sfx("correct");flash("✓ "+t.word.toUpperCase(),false);if(power>=4){power=0;powerUntil=now+7500;sfx("power")}if(wordIndex>=verseKeys.length){finishVerse(true);return}else spawnVerseWords()}else{score=Math.max(0,score-10);combo=0;wordTargets.splice(i,1);flash("WRONG WORD",true)}break}for(let g of ghosts)if(dist(player,g)<.55){if(now<powerUntil){g.r=player.r-12;score+=200}else{hurtVerse(now);return}}verseGlitch-=dt*(.36+wordIndex*.02);if(player.r>verseGlitch-.4)hurtVerse(now);cameraTop=clamp(player.r-visibleRows*.68,0,WORLD_ROWS-visibleRows);updateVerseHud()}
function hurtVerse(now){if(now<invulnUntil)return;lives--;sfx("hit");flash("GOT YOU",true);if(lives<=0){finishVerse(false);return}resetPlayer(13,Math.max(3,Math.round(player.r-5)|1));invulnUntil=now+1800;ghosts=[];spawnHeroGhost("chaser",player.r-8);spawnHeroGhost("ambush",player.r-12);spawnHeroGhost("patrol",player.r-16);spawnVerseWords();verseGlitch=Math.max(verseGlitch,player.r+10)}
function finishVerse(win){running=false;stopMusic();$("endTitle").textContent=win?"VERSE COMPLETE!":"RUN OVER";$("endText").textContent=win?"Romans 3:23 completed in order. Score: "+score:"You reached "+wordIndex+" of "+verseKeys.length+" words. Score: "+score;$("end").classList.add("show")}
function finishHero(win){running=false;stopMusic();$("endTitle").textContent=win?"AB001 MASTERED!":"MISSION FAILED";$("endText").textContent=win?'“And into the land of Canaan they came.” — Genesis 12:5 KJV\n\nYou assembled the caravan, departed Haran, crossed the journey and reached Canaan. Score: '+score:"The caravan did not reach Canaan this run. Score: "+score;$("end").classList.add("show")}
function terrainColors(r){if(mode==="verse")return{bg:"#03050b",wall:"#111a4d",edge:"#273b9b",dot:"#f4efc7"};if(r>=48)return{bg:"#160d06",wall:"#6e3f1c",edge:"#c8893e",dot:"#ffd879"};if(r>=34)return{bg:"#24170a",wall:"#7e5927",edge:"#d1a150",dot:"#ffe29b"};if(r>=10)return{bg:"#130f0b",wall:"#514333",edge:"#9b8058",dot:"#f0d8a3"};return{bg:"#07110a",wall:"#21452b",edge:"#6eaa63",dot:"#dff3b1"}}
function drawWall(x,y,col){ctx.fillStyle=col.wall;ctx.fillRect(x+tile*.04,y+tile*.04,tile*.92,tile*.92);ctx.fillStyle=col.edge;ctx.fillRect(x+tile*.09,y+tile*.09,tile*.82,tile*.16);ctx.fillStyle="#0005";ctx.fillRect(x+tile*.09,y+tile*.75,tile*.82,tile*.16)}
function drawGate(){if(mode!=="hero")return;let y=(47-cameraTop)*tile;if(y<-tile||y>ch)return;ctx.save();ctx.strokeStyle="#d7aa55";ctx.lineWidth=2*dpr;ctx.fillStyle="#3b2913";if(!journeyFlags.gate){for(let c=11;c<=15;c++){let x=c*tile;ctx.fillRect(x,y,tile,tile);ctx.strokeRect(x+2,y+2,tile-4,tile-4)}}else{ctx.fillRect(11*tile,y,tile,tile);ctx.fillRect(15*tile,y,tile,tile);ctx.beginPath();ctx.moveTo(11*tile,y);ctx.lineTo(11*tile,y+tile);ctx.moveTo(16*tile,y);ctx.lineTo(16*tile,y+tile);ctx.stroke()}ctx.fillStyle="#ffe59a";ctx.font=`900 ${Math.max(9*dpr,tile*.28)}px system-ui`;ctx.textAlign="center";ctx.fillText(journeyFlags.gate?"ROAD OPEN":"HARAN GATE",13.5*tile,y-tile*.18);ctx.restore()}
function drawTarget(t){let x=(t.c+.5)*tile,y=(t.r-cameraTop+.5)*tile,rad=tile*.35;ctx.save();ctx.shadowBlur=14*dpr;ctx.shadowColor="#ffd25c99";ctx.fillStyle="#fff1bd";ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#3a250d";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`1000 ${Math.max(8*dpr,tile*.25)}px system-ui`;let sym=t.kind==="person"?(t.id==="sarai"?"S":"L"):t.kind==="camel"?"🐪":t.kind==="flock"?"🐑":t.kind==="group"?"👥":"📦";ctx.fillText(sym,x,y-rad*.08);ctx.font=`900 ${Math.max(6*dpr,tile*.17)}px system-ui`;ctx.fillText(t.name,x,y+rad*.72);ctx.restore()}
function drawFollower(f,i){let p=pathSample(17+i*15),x=(p.c+.5)*tile,y=(p.r-cameraTop+.5)*tile,rad=tile*.24;ctx.save();ctx.globalAlpha=.95;ctx.fillStyle=i===0?"#ffd7a1":"#f3e1aa";ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#7b5627";ctx.lineWidth=1*dpr;ctx.stroke();ctx.fillStyle="#251708";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`1000 ${Math.max(6*dpr,tile*.17)}px system-ui`;let s=f.kind==="person"?f.name[0]:f.kind==="camel"?"C":f.kind==="flock"?"F":f.kind==="group"?"H":"G";ctx.fillText(s,x,y);ctx.restore()}
function drawGhost(g,now){let x=(g.c+.5)*tile,y=(g.r-cameraTop+.5)*tile,rad=tile*.30,v=now<powerUntil;ctx.fillStyle=v?"#315aff":g.color;ctx.beginPath();ctx.arc(x,y-rad*.12,rad,Math.PI,0);ctx.lineTo(x+rad,y+rad*.8);ctx.lineTo(x+rad*.42,y+rad*.48);ctx.lineTo(x,y+rad*.8);ctx.lineTo(x-rad*.42,y+rad*.48);ctx.lineTo(x-rad,y+rad*.8);ctx.closePath();ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(x-rad*.3,y-rad*.18,rad*.21,0,Math.PI*2);ctx.arc(x+rad*.3,y-rad*.18,rad*.21,0,Math.PI*2);ctx.fill()}
function drawHazard(h,now){if(mode!=="hero")return;let x=(h.c+.5)*tile,y=(h.r-cameraTop+.5)*tile;if(y<-tile*2||y>ch+tile*2)return;ctx.save();if(h.type==="cart"){ctx.fillStyle="#8b5526";ctx.fillRect(x-tile*.43,y-tile*.22,tile*.86,tile*.44);ctx.fillStyle="#d19a50";ctx.fillRect(x-tile*.30,y-tile*.36,tile*.6,tile*.20);ctx.fillStyle="#22150a";ctx.beginPath();ctx.arc(x-tile*.28,y+tile*.28,tile*.12,0,Math.PI*2);ctx.arc(x+tile*.28,y+tile*.28,tile*.12,0,Math.PI*2);ctx.fill()}else if(h.type==="dust"){ctx.strokeStyle="#e0b26c";ctx.globalAlpha=.65;ctx.lineWidth=2*dpr;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(x,y,(.18+i*.11)*tile,0,Math.PI*1.55);ctx.stroke()}}else if(h.type==="rock"&&h.armed){if(h.warn>0){ctx.strokeStyle="#ffdf70";ctx.globalAlpha=.6+.3*Math.sin(now/70);ctx.lineWidth=2*dpr;ctx.beginPath();ctx.arc(x,y,tile*(.35+.18*h.warn),0,Math.PI*2);ctx.stroke();ctx.fillStyle="#ffe38f";ctx.font=`900 ${Math.max(7*dpr,tile*.18)}px system-ui`;ctx.textAlign="center";ctx.fillText("!",x,y)}else{let yy=y+(h.fall||0)*tile*.35;ctx.fillStyle="#796755";ctx.beginPath();ctx.arc(x,yy,tile*.34,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#b8a084";ctx.stroke()}}ctx.restore()}
function drawSandstorm(){if(mode!=="hero"||!sandstormActive)return;let y=(sandstormRow-cameraTop)*tile;if(y>ch)return;ctx.save();ctx.globalAlpha=.58;let grad=ctx.createLinearGradient(0,Math.max(0,y-80*dpr),0,ch);grad.addColorStop(0,"#c38b3a00");grad.addColorStop(.35,"#b9782a88");grad.addColorStop(1,"#6a3f14e8");ctx.fillStyle=grad;ctx.fillRect(0,Math.max(0,y-80*dpr),cw,ch);for(let i=0;i<35;i++){ctx.fillStyle=i%2?"#ffd58a55":"#b7752f55";ctx.fillRect(rnd()*cw,Math.max(0,y-30*dpr)+rnd()*(ch-Math.max(0,y-30*dpr)),(8+rnd()*40)*dpr,(1+rnd()*4)*dpr)}ctx.restore()}
function drawPlayer(now){let x=(player.c+.5)*tile,y=(player.r-cameraTop+.5)*tile,rad=tile*.37,ang=player.dir.x<0?Math.PI:player.dir.y<0?-Math.PI/2:player.dir.y>0?Math.PI/2:0,m=.15+.14*(.5+.5*Math.sin(player.mouth));ctx.save();ctx.translate(x,y);ctx.rotate(ang);ctx.globalAlpha=(now<invulnUntil&&Math.floor(now/90)%2)?0.35:1;ctx.fillStyle="#ffdc35";ctx.shadowBlur=11*dpr;ctx.shadowColor="#ffd93d88";ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,rad,m*Math.PI,(2-m)*Math.PI);ctx.closePath();ctx.fill();if(mode==="hero"){ctx.shadowBlur=0;ctx.rotate(-ang);ctx.fillStyle="#6f3a1c";ctx.fillRect(-rad*.58,-rad*.70,rad*1.15,rad*.22);ctx.fillStyle="#f5d79c";ctx.fillRect(-rad*.40,-rad*.48,rad*.80,rad*.10)}ctx.restore()}
function drawVerseTargets(){wordTargets.forEach(t=>{let x=(t.c+.5)*tile,y=(t.r-cameraTop+.5)*tile,fs=Math.max(10*dpr,tile*.30);ctx.font=`900 ${fs}px system-ui`;let w=Math.max(tile*.9,ctx.measureText(t.word).width+10*dpr),h=tile*.55;ctx.fillStyle="#fff8d7";ctx.fillRect(x-w/2,y-h/2,w,h);ctx.strokeStyle="#ffd94d";ctx.strokeRect(x-w/2,y-h/2,w,h);ctx.fillStyle="#10131d";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(t.word,x,y)})}
function draw(now){let base=terrainColors(player?player.r:69);ctx.fillStyle=base.bg;ctx.fillRect(0,0,cw,ch);let start=Math.max(0,Math.floor(cameraTop)-1),end=Math.min(WORLD_ROWS-1,Math.ceil(cameraTop+visibleRows)+1);for(let r=start;r<=end;r++){let col=terrainColors(r);for(let c=0;c<COLS;c++){let x=c*tile,y=(r-cameraTop)*tile;if(grid[r][c]==="#"||(r===47&&!journeyFlags.gate&&c>=11&&c<=15))drawWall(x,y,col);else if(!visitedDots.has(key(c,r))){ctx.fillStyle=col.dot;ctx.beginPath();ctx.arc(x+tile/2,y+tile/2,Math.max(1.3*dpr,tile*.052),0,Math.PI*2);ctx.fill()}}}if(mode==="hero"){drawGate();targets.forEach(drawTarget);followers.forEach(drawFollower);hazards.forEach(h=>drawHazard(h,now))}else drawVerseTargets();ghosts.forEach(g=>drawGhost(g,now));drawSandstorm();drawPlayer(now)}
function resize(){dpr=Math.min(2,window.devicePixelRatio||1);let cssW=window.innerWidth,cssH=Math.max(1,window.innerHeight-42);canvas.style.width=cssW+"px";canvas.style.height=cssH+"px";canvas.width=Math.round(cssW*dpr);canvas.height=Math.round(cssH*dpr);cw=canvas.width;ch=canvas.height;tile=cw/COLS;visibleRows=ch/tile}
function loop(ts){let dt=Math.min(.034,(ts-lastTime)/1000||0);lastTime=ts;try{if(mode==="hero")updateHero(dt,ts);else updateVerse(dt,ts);draw(ts)}catch(e){console.error(e);flash("GAME ERROR",true)}requestAnimationFrame(loop)}
function ensureLoop(){if(loopStarted)return;loopStarted=true;lastTime=performance.now();requestAnimationFrame(loop)}
function musicIntensity(){if(!player)return .1;let nearest=20;ghosts.forEach(g=>nearest=Math.min(nearest,dist(player,g)));let heat=clamp((7-nearest)/6,0,1),storm=mode==="hero"&&sandstormActive?clamp((9-(sandstormRow-player.r))/8,0,1):0;return clamp(.1+heat*.5+storm*.4+(performance.now()<powerUntil?.15:0),0,1)}
function freq(n){return 440*Math.pow(2,(n-69)/12)}function initAudio(){if(audio)return;let AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio=new AC();master=audio.createGain();filter=audio.createBiquadFilter();filter.type="lowpass";filter.frequency.value=2300;filter.connect(master);master.connect(audio.destination);master.gain.value=.0001;musicTimer=setInterval(scheduleMusic,30)}function tone(n,t,dur,vol,type){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type||"square";o.frequency.value=freq(n);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(filter);o.start(t);o.stop(t+dur+.02)}function scheduleMusic(){if(!audio||!running||!musicOn)return;let horizon=audio.currentTime+.12;if(nextBeat<audio.currentTime-.2)nextBeat=audio.currentTime+.02;while(nextBeat<horizon){let q=musicIntensity(),bpm=100+q*82,step=60/bpm/4,pat=mode==="hero"?[0,3,7,10,7,3,5,8,0,3,7,12,10,7,5,2]:[0,3,7,10,7,3,12,10,0,3,7,12,10,7,3,-2],root=mode==="hero"?45:48;if(q>.08&&(q>.45||beat%2===0))tone(root+pat[beat%16],nextBeat,.08,.018+.015*q,"square");if(beat%4===0)tone(root-12+(beat>=8?7:0),nextBeat,.14,.03+.02*q,"triangle");filter.frequency.setTargetAtTime(1500+q*4700,audio.currentTime,.08);nextBeat+=step;beat=(beat+1)%16}}
function startMusic(){if(!musicOn)return;initAudio();if(!audio)return;if(audio.state==="suspended")audio.resume();beat=0;nextBeat=audio.currentTime+.03;master.gain.setTargetAtTime(musicVol*.38,audio.currentTime,.06)}function stopMusic(){if(audio&&master)master.gain.setTargetAtTime(.0001,audio.currentTime,.05)}function sfx(kind){if(!audio||!musicOn)return;let t=audio.currentTime+.01;if(kind==="correct"){tone(76,t,.08,.05,"triangle");tone(81,t+.05,.09,.04,"triangle")}else if(kind==="power"){[67,72,76,79].forEach((n,i)=>tone(n,t+i*.045,.14,.04,"square"))}else if(kind==="hit"){tone(34,t,.22,.06,"sawtooth")}else if(kind==="eat"){[72,79,84].forEach((n,i)=>tone(n,t+i*.04,.09,.04,"square"))}else if(kind==="gate"){[55,60,67,72].forEach((n,i)=>tone(n,t+i*.07,.18,.05,"triangle"))}}
async function fullscreenLandscape(){try{if(document.documentElement.requestFullscreen&&!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch(e){}try{if(screen.orientation&&screen.orientation.lock)await screen.orientation.lock("landscape")}catch(e){}}
async function begin(which){initAudio();if(audio&&audio.state==="suspended")audio.resume();document.body.classList.add("playing");$("end").classList.remove("show");$("story").classList.remove("show");firstSwipe=false;$("hint").classList.remove("hide");$("queue").textContent="•";if(which==="hero"){initHero();$("ref").innerHTML='AB001 <em>HERO MISSION</em>'}else initVerse();resize();cameraTop=clamp(player.r-visibleRows*.68,0,WORLD_ROWS-visibleRows);running=false;ensureLoop();await fullscreenLandscape();setTimeout(resize,120);setTimeout(resize,420);if(which==="hero")startStory();else{running=true;startMusic()}}
function continueStory(){$("story").classList.remove("show");running=true;startMusic();invulnUntil=performance.now()+1200}
function backToSetup(){running=false;stopMusic();document.body.classList.remove("playing");$("end").classList.remove("show");$("story").classList.remove("show");try{if(screen.orientation&&screen.orientation.unlock)screen.orientation.unlock()}catch(e){}try{if(document.fullscreenElement&&document.exitFullscreen)document.exitFullscreen()}catch(e){}}
var game=$("game");game.addEventListener("pointerdown",e=>{if(e.target&&e.target.closest&&e.target.closest("button"))return;swipeId=e.pointerId;sx=e.clientX;sy=e.clientY;swipeFired=false;try{game.setPointerCapture(e.pointerId)}catch(err){}},{passive:false});game.addEventListener("pointermove",e=>{if(swipeId!==e.pointerId||swipeFired)return;let dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<16)return;swipeFired=true;let n=Math.abs(dx)>Math.abs(dy)?(dx>0?"right":"left"):(dy>0?"down":"up");queueDir(n);if(!firstSwipe){firstSwipe=true;$("hint").classList.add("hide")}e.preventDefault()},{passive:false});game.addEventListener("pointerup",e=>{if(swipeId===e.pointerId)swipeId=null});game.addEventListener("pointercancel",e=>{if(swipeId===e.pointerId)swipeId=null});window.addEventListener("resize",()=>{if(document.body.classList.contains("playing"))resize()});window.addEventListener("orientationchange",()=>setTimeout(resize,250));$("startHero").addEventListener("click",()=>begin("hero"));$("startVerse").addEventListener("click",()=>begin("verse"));$("storyGo").addEventListener("click",continueStory);$("exit").addEventListener("click",backToSetup);$("back").addEventListener("click",backToSetup);$("again").addEventListener("click",()=>begin(mode));$("musicToggle").addEventListener("click",function(){musicOn=!musicOn;this.textContent=musicOn?"ON":"OFF";this.classList.toggle("on",musicOn);if(!musicOn)stopMusic();else if(running)startMusic()});$("volume").addEventListener("input",function(){musicVol=Number(this.value)/100;if(audio&&master&&musicOn)master.gain.setTargetAtTime(musicVol*.38,audio.currentTime,.04)});
