"use strict";

// Verse Chomp fixed-course upgrade: permanent word rooms, biblical predators,
// streak scoring, courage pickups, section checkpoints, and visible darkness.
var verseStreak=0,bestVerseStreak=0,wrongCount=0,dangerBoostUntil=0,sectionShown=[false,false],finalRushStarted=false,courageItems=[],verseRooms=[];

function setPowerIcon(icon){let s=$("powerStat");if(s&&s.firstChild)s.firstChild.nodeValue=icon+" "}
function enemyAnimal(type){return type==="chaser"?"lion":type==="ambush"?"serpent":"wolf"}
function animalName(g){return(g.animal||enemyAnimal(g.type)).toUpperCase()}
function spawnVerseEnemy(type,r){let p=randomOpenIn(Math.max(2,r-2),Math.min(WORLD_ROWS-2,r+2)),base=type==="chaser"?2.75:type==="ambush"?2.5:2.3;ghosts.push({type,animal:enemyAnimal(type),c:p.c,r:p.r,dir:{x:rnd()<.5?-1:1,y:0},lastCenter:"",speed:base,color:type==="chaser"?"#d89b38":type==="ambush"?"#5ca55f":"#8f9bab"})}
function currentVerseTarget(){return wordTargets.find(t=>t.isCorrect&&t.roomIndex===wordIndex&&!t.collected)||null}
function sendEnemyAway(g){let lo=clamp(player.r+9,2,WORLD_ROWS-2),hi=clamp(player.r+14,lo,WORLD_ROWS-2),p=randomOpenIn(lo,hi);g.r=p.r;g.c=p.c;g.lastCenter="";g.dir={x:rnd()<.5?-1:1,y:0}}

ghostTarget=function(g){if(g.type==="ambush")return{c:player.c+player.dir.x*4,r:player.r+player.dir.y*4};if(g.type==="patrol"){if(mode==="verse"){let t=currentVerseTarget();if(t)return t}return{c:player.c,r:g.r}}return player};
stepGhost=function(g,dt,now){let rc=Math.round(g.c),rr=Math.round(g.r),near=Math.abs(g.c-rc)<.13&&Math.abs(g.r-rr)<.13,k=key(rc,rr);if(near&&g.lastCenter!==k){g.c=rc;g.r=rr;g.dir=chooseGhostDir(g,now);g.lastCenter=k}let boost=mode==="verse"&&now<dangerBoostUntil?1.22:1,final=mode==="verse"&&wordIndex>=8?1.12:1,sp=g.speed*boost*final*(now<powerUntil?.68:1);g.c+=g.dir.x*sp*dt;g.r+=g.dir.y*sp*dt};

function buildVerseCourse(){let rows=[287,277,267,257,247,237,227,217,207,197,187,177],correctCols=[5,21,13,5,21,13,21,5,13,21,5,13],decoys=[["Because","As"],["many","some"],["hath","were"],["sin","fallen"],["but","for"],["fall","are"],["behind","under"],["from","unto"],["his","that"],["grace","righteousness"],["from","unto"],["Christ","heaven"]];wordTargets=[];verseRooms=[];for(let i=0;i<verseWords.length;i++){let row=rows[i],cols=[5,13,21],cc=correctCols[i],others=cols.filter(c=>c!==cc),label=verseWords[i];verseRooms.push({index:i,r:row});wordTargets.push({label,word:verseKeys[i],isCorrect:true,roomIndex:i,c:cc,r:row,collected:false,cooldownUntil:0});others.forEach((c,j)=>wordTargets.push({label:decoys[i][j],word:decoys[i][j].toLowerCase().replace(/[^a-z]/g,""),isCorrect:false,roomIndex:i,c,r:row,collected:false,cooldownUntil:0}))}courageItems=[{c:23,r:253,collected:false},{c:3,r:213,collected:false},{c:23,r:183,collected:false}]}
function verseMultiplier(){return Math.min(4,1+Math.floor(verseStreak/3))}
function currentSection(){return wordIndex<4?1:wordIndex<8?2:3}
function handleVerseCheckpoint(now){if(wordIndex===4&&!sectionShown[0]){sectionShown[0]=true;checkpoint={c:Math.round(player.c),r:Math.round(player.r)};score+=400;verseGlitch=Math.max(verseGlitch,player.r+9);spawnVerseEnemy("ambush",player.r+8);showCheckpoint("ROMANS 3:23 KJV","SECTION 1 CLEARED",verseWords.slice(0,4).join(" "),"The course stays exactly where it is. Section 2 adds a serpent that tries to cut off your route.","START SECTION 2");return true}if(wordIndex===8&&!sectionShown[1]){sectionShown[1]=true;checkpoint={c:Math.round(player.c),r:Math.round(player.r)};score+=700;finalRushStarted=true;verseGlitch=Math.max(verseGlitch,player.r+7);spawnVerseEnemy("chaser",player.r+7);dangerBoostUntil=now+7000;showCheckpoint("ROMANS 3:23 KJV","FINAL RUSH",verseWords.slice(0,8).join(" "),"Four words remain. The lion is faster, the wolf guards the route, and the darkness closes in more quickly.","BEGIN FINAL RUSH");return true}return false}
function wrongVerseChoice(t,now){t.cooldownUntil=now+1800;score=Math.max(0,score-50);verseStreak=0;wrongCount++;dangerBoostUntil=now+5000;verseGlitch=Math.max(player.r+2.2,verseGlitch-3.5);if(ghosts.length<5)spawnVerseEnemy(wrongCount%3===0?"ambush":"chaser",player.r+6);sfx("hit");flash("WRONG WORD — "+(wrongCount%3===0?"SERPENT":"LION")+" RELEASED!",true)}
function collectCourage(item,now){item.collected=true;powerUntil=now+7000;score+=150;sfx("power");flash("COURAGE! PREDATORS FLEE",false)}

var baseInitHero=initHero;
initHero=function(){baseInitHero();setPowerIcon("⚡")};

initVerse=function(){mode="verse";COLS=27;WORLD_ROWS=301;START_ROW=297;score=0;lives=3;power=0;powerUntil=0;wordIndex=0;combo=0;verseStreak=0;bestVerseStreak=0;wrongCount=0;dangerBoostUntil=0;sectionShown=[false,false];finalRushStarted=false;visitedDots=new Set();ghosts=[];wordTargets=[];courageItems=[];verseRooms=[];verseGlitch=305;buildVerseWorld();buildVerseCourse();resetPlayer(13,297);checkpoint={c:13,r:297};invulnUntil=performance.now()+1800;spawnVerseEnemy("chaser",291);spawnVerseEnemy("patrol",283);setPowerIcon("🛡️");$("ref").innerHTML='ROMANS 3:23 KJV <em>VERSE CHOMP</em>';$("zone").textContent="SECTION 1";$("powerStat").style.display="";updateVerseHud()};
updateVerseHud=function(){let done=verseWords.slice(0,wordIndex).join(" "),section=currentSection(),mult=verseMultiplier();$("objective").textContent=(done?done+" ":"")+(wordIndex<verseWords.length?"______":"✓ VERSE COMPLETE");$("missionText").textContent=(section===3?"FINAL RUSH • ":"SECTION "+section+" • ")+"CHOMP THE NEXT KJV WORD • x"+mult;$("missionCount").textContent=wordIndex+"/"+verseWords.length;$("missionBarFill").style.width=wordIndex/verseWords.length*100+"%";$("zone").textContent=section===3?"FINAL RUSH":"SECTION "+section;$("lives").textContent=lives;$("score").textContent=score;$("power").textContent=performance.now()<powerUntil?"ON":"FIND"};
updateVerse=function(dt,now){if(!running)return;stepPlayer(dt);ghosts.forEach(g=>stepGhost(g,dt,now));for(let item of courageItems)if(!item.collected&&dist(player,item)<.56){collectCourage(item,now);break}for(let t of wordTargets){if(t.collected||now<t.cooldownUntil||dist(player,t)>=.5)continue;if(t.isCorrect&&t.roomIndex===wordIndex){t.collected=true;verseStreak++;bestVerseStreak=Math.max(bestVerseStreak,verseStreak);let mult=verseMultiplier();score+=100*mult;wordIndex++;sfx("correct");flash("✓ "+t.label.toUpperCase()+" • x"+mult,false);if(wordIndex>=verseKeys.length){finishVerse(true);return}if(handleVerseCheckpoint(now))return}else wrongVerseChoice(t,now);break}for(let g of ghosts)if(dist(player,g)<.55){if(now<powerUntil){score+=75;sendEnemyAway(g);sfx("eat");flash(animalName(g)+" FLED FROM COURAGE! +75",false)}else{hurtVerse(now,animalName(g));return}break}verseGlitch-=dt*((wordIndex>=8?1.05:.72)+wordIndex*.035);if(player.r>verseGlitch-.35){hurtVerse(now,"DARKNESS");return}cameraTop=clamp(player.r-visibleRows*.68,0,WORLD_ROWS-visibleRows);updateVerseHud()};
hurtVerse=function(now,reason){if(now<invulnUntil)return;lives--;sfx("hit");verseStreak=0;flash((reason||"DANGER")+" GOT YOU",true);if(lives<=0){finishVerse(false);return}resetPlayer(checkpoint.c,checkpoint.r);invulnUntil=now+1800;powerUntil=0;let section=currentSection();ghosts=[];spawnVerseEnemy("chaser",player.r+7);spawnVerseEnemy("patrol",player.r+11);if(section>=2)spawnVerseEnemy("ambush",player.r+9);if(section===3)spawnVerseEnemy("chaser",player.r+13);verseGlitch=Math.max(verseGlitch,player.r+8);updateVerseHud()};
finishVerse=function(win){running=false;stopMusic();$("endTitle").textContent=win?"VERSE COMPLETE!":"RUN OVER";$("endText").textContent=win?"Romans 3:23 completed in order. Score: "+score+" • Best word streak: "+bestVerseStreak:"You reached "+wordIndex+" of "+verseKeys.length+" words. Score: "+score+" • Best word streak: "+bestVerseStreak;$("end").classList.add("show")};

drawGhost=function(g,now){let x=(g.c+.5)*tile,y=(g.r-cameraTop+.5)*tile,animal=g.animal||enemyAnimal(g.type),icon=animal==="lion"?"🦁":animal==="serpent"?"🐍":"🐺";ctx.save();ctx.globalAlpha=now<powerUntil?.55:1;ctx.shadowBlur=now<powerUntil?4*dpr:10*dpr;ctx.shadowColor=now<powerUntil?"#8bd5ff":"#ffbd55";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`${Math.max(16*dpr,tile*.74)}px Apple Color Emoji,Segoe UI Emoji,sans-serif`;ctx.fillText(icon,x,y);ctx.shadowBlur=0;ctx.fillStyle=now<powerUntil?"#bcecff":"#fff0bd";ctx.font=`900 ${Math.max(6*dpr,tile*.14)}px system-ui`;ctx.fillText(animal.toUpperCase(),x,y+tile*.46);ctx.restore()};
function drawVerseDarkness(){if(mode!=="verse")return;let y=(verseGlitch-cameraTop)*tile;if(y>ch+tile)return;ctx.save();let top=clamp(y,0,ch),grad=ctx.createLinearGradient(0,Math.max(0,top-tile*1.5),0,ch);grad.addColorStop(0,"#7c101000");grad.addColorStop(.22,"#5b090988");grad.addColorStop(1,"#050000f2");ctx.fillStyle=grad;ctx.fillRect(0,Math.max(0,top-tile*1.5),cw,ch);ctx.strokeStyle="#ff493f";ctx.globalAlpha=.75+.2*Math.sin(performance.now()/100);ctx.lineWidth=Math.max(2*dpr,tile*.08);ctx.beginPath();ctx.moveTo(0,top);ctx.lineTo(cw,top);ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle="#ffb1a9";ctx.font=`900 ${Math.max(7*dpr,tile*.18)}px system-ui`;ctx.textAlign="center";ctx.fillText("DARKNESS CLOSING IN",cw/2,Math.max(tile*.4,top-tile*.2));ctx.restore()}
function drawVerseRoom(room){let y=(room.r-cameraTop+.5)*tile;if(y<-tile||y>ch+tile)return;let active=room.index===wordIndex;ctx.save();ctx.globalAlpha=active?.9:.28;ctx.strokeStyle=active?"#ffd94d":"#6a7dd6";ctx.lineWidth=active?2*dpr:1*dpr;ctx.setLineDash([6*dpr,6*dpr]);ctx.beginPath();ctx.moveTo(tile*1.2,y-tile*.72);ctx.lineTo(cw-tile*1.2,y-tile*.72);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=active?"#ffe981":"#9da8e8";ctx.font=`900 ${Math.max(6*dpr,tile*.15)}px system-ui`;ctx.textAlign="center";ctx.fillText(active?"NEXT WORD — CHOOSE CAREFULLY":"VERSE WORD "+(room.index+1),cw/2,y-tile*.86);ctx.restore()}
drawVerseTargets=function(){verseRooms.forEach(drawVerseRoom);wordTargets.forEach(t=>{let x=(t.c+.5)*tile,y=(t.r-cameraTop+.5)*tile;if(y<-tile||y>ch+tile)return;let fs=Math.max(10*dpr,tile*.30);ctx.save();ctx.font=`900 ${fs}px system-ui`;let w=Math.max(tile*.9,ctx.measureText(t.label).width+10*dpr),h=tile*.55,active=t.roomIndex===wordIndex;ctx.globalAlpha=t.collected?.38:t.roomIndex<wordIndex?.36:1;ctx.fillStyle=t.collected?"#c7e8ba":"#fff8d7";ctx.fillRect(x-w/2,y-h/2,w,h);ctx.strokeStyle=t.collected?"#67a85b":active?"#ffd94d":"#6876bd";ctx.lineWidth=active?2*dpr:1*dpr;ctx.strokeRect(x-w/2,y-h/2,w,h);ctx.fillStyle="#10131d";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(t.collected?"✓ "+t.label:t.label,x,y);ctx.restore()});courageItems.forEach(item=>{if(item.collected)return;let x=(item.c+.5)*tile,y=(item.r-cameraTop+.5)*tile;if(y<-tile||y>ch+tile)return;ctx.save();ctx.shadowBlur=15*dpr;ctx.shadowColor="#9fe8ff";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`${Math.max(16*dpr,tile*.72)}px Apple Color Emoji,Segoe UI Emoji,sans-serif`;ctx.fillText("🛡️",x,y);ctx.shadowBlur=0;ctx.fillStyle="#c9f2ff";ctx.font=`900 ${Math.max(6*dpr,tile*.14)}px system-ui`;ctx.fillText("COURAGE",x,y+tile*.48);ctx.restore()})};

draw=function(now){let base=terrainColors(player?player.r:69);ctx.fillStyle=base.bg;ctx.fillRect(0,0,cw,ch);let start=Math.max(0,Math.floor(cameraTop)-1),end=Math.min(WORLD_ROWS-1,Math.ceil(cameraTop+visibleRows)+1);for(let r=start;r<=end;r++){let col=terrainColors(r);for(let c=0;c<COLS;c++){let x=c*tile,y=(r-cameraTop)*tile;if(grid[r][c]==="#"||(r===47&&!journeyFlags.gate&&c>=11&&c<=15))drawWall(x,y,col);else if(!visitedDots.has(key(c,r))){ctx.fillStyle=col.dot;ctx.beginPath();ctx.arc(x+tile/2,y+tile/2,Math.max(1.3*dpr,tile*.052),0,Math.PI*2);ctx.fill()}}}if(mode==="hero"){drawGate();targets.forEach(drawTarget);followers.forEach(drawFollower);hazards.forEach(h=>drawHazard(h,now))}else drawVerseTargets();ghosts.forEach(g=>drawGhost(g,now));drawSandstorm();drawVerseDarkness();drawPlayer(now)};

musicIntensity=function(){if(!player)return .1;let nearest=20;ghosts.forEach(g=>nearest=Math.min(nearest,dist(player,g)));let heat=clamp((7-nearest)/6,0,1),storm=mode==="hero"&&sandstormActive?clamp((9-(sandstormRow-player.r))/8,0,1):0,dark=mode==="verse"?clamp((9-(verseGlitch-player.r))/8,0,1):0;return clamp(.1+heat*.5+storm*.4+dark*.35+(performance.now()<powerUntil?.15:0),0,1)};
