(() => {
'use strict';
const {VERSES,clean,key,tokens,choices,multiplier,medal}=SkyCore;
const $=id=>document.getElementById(id);
const canvas=$('world'),ctx=canvas.getContext('2d',{alpha:false});
const laneButtons=[...document.querySelectorAll('[data-lane]')];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const STORE='hide-the-word-skybreak-v1';
let saved={best:{},medals:{},sound:true,mission:0,difficulty:'normal'};
try{const data=JSON.parse(localStorage.getItem(STORE)||'null');if(data&&typeof data==='object'){saved={...saved,...data,best:data.best||{},medals:data.medals||{}};}}catch{}
function save(){try{localStorage.setItem(STORE,JSON.stringify(saved));}catch{}}
let width=innerWidth,height=innerHeight,dpr=1,clock=0,last=0,noticeTime=0,trackHorizon=0;
let state='menu',run=null,gate=null,hazards=[],particles=[],beams=[],rings=[],lane=1,laneVisual=1,jumpTime=0,invincible=0,burstTime=0,screenShake=0;
let audio=null,audioGain=null,musicTime=0,musicStep=0;
const scenery=new Image();scenery.src='sky-islands.webp';
const modes=['LEARN THE ROUTE','TRUST YOUR MEMORY','BREAK THE STORM'];
const settings={easy:{time:4.0,hazard:.23,hearts:5},normal:{time:3.0,hazard:.5,hearts:4},hard:{time:2.35,hazard:.8,hearts:3}};
const starfield=Array.from({length:65},()=>({x:Math.random(),y:Math.random(),s:Math.random()*1.6+.4}));
const upgradeDefs=[
 {id:'heart',title:'♥ Bigger heart',desc:'Gain one extra heart container and refill all hearts.'},
 {id:'shield',title:'◈ Cloud shield',desc:'Block the next two hazards. A wrong word still costs a heart.'},
 {id:'slow',title:'◷ Time glider',desc:'Get 25% more thinking time at every word gate.'},
 {id:'charge',title:'ϟ Quick charge',desc:'Your burst charges in only three correct words.'}
];
function resize(){width=canvas.clientWidth||innerWidth;height=canvas.clientHeight||innerHeight;dpr=Math.min(devicePixelRatio||1,1.75);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(run)fitHUD();}
addEventListener('resize',resize);resize();
function initAudio(){if(!saved.sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(!audioGain){audioGain=audio.createGain();audioGain.gain.value=.20;audioGain.connect(audio.destination);}audio.resume().catch(()=>{});}catch{}}
function note(freq,duration=.12,type='sine',volume=.25,delay=0){if(!audio||!saved.sound||audio.state!=='running')return;try{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(audioGain);o.start(t);o.stop(t+duration+.03);}catch{}}
function sound(kind){if(kind==='correct'){[523,659,784].forEach((n,i)=>note(n,.14,'sine',.22,i*.055));}else if(kind==='hit'){note(100,.23,'sawtooth',.18);note(65,.2,'triangle',.2,.1);}else if(kind==='jump'){note(390,.12,'triangle');note(680,.15,'sine',.2,.06);}else if(kind==='win'){[523,659,784,1047,1318].forEach((n,i)=>note(n,.4,'triangle',.25,i*.1));}else if(kind==='burst'){[130,260,520,1040].forEach((n,i)=>note(n,.35,'triangle',.35,i*.035));}else note(330,.08,'sine',.12);}
function soundtrack(dt){if(!saved.sound||!run)return;musicTime-=dt;if(musicTime<=0){musicTime=run.stage===2?.23:.3;const melody=[0,7,12,7,3,10,15,10,5,12,17,12,3,10,15,19];const base=run.stage===2?146.83:130.81;note(base*Math.pow(2,melody[musicStep%16]/12),.25,'triangle',.045);if(musicStep%4===0)note(base/2,.28,'sine',.2);musicStep++;}}
function notice(text,seconds=1.3){$('announcement').textContent=text;$('announcement').classList.add('visible');noticeTime=seconds;}
function emit(x,y,color,count=18,force=1){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=(45+Math.random()*170)*force;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5+Math.random()*.45,max:1,color,size:2+Math.random()*5});}if(particles.length>160)particles.splice(0,particles.length-160);}
function fitHUD(){const hudBottom=$('hud').getBoundingClientRect().bottom||0,verseBottom=$('verse').getBoundingClientRect().bottom||0;const top=Math.max(hudBottom,verseBottom)+8;$('target').style.top=top+'px';trackHorizon=Math.max(height*.40,top+($('target').getBoundingClientRect().height||50)+12);}
function setText(el,text){if(el.textContent!==String(text))el.textContent=text;}
function showOverlay(kicker,title,body,actions){$('overlayKicker').textContent=kicker;$('overlayTitle').textContent=title;$('overlayBody').innerHTML=body;$('overlayActions').replaceChildren();for(const action of actions){const b=document.createElement('button');if(action.primary)b.className='primary';b.textContent=action.label;if(action.desc){const small=document.createElement('small');small.textContent=action.desc;b.append(small);}b.addEventListener('click',action.fn);$('overlayActions').append(b);}$('overlay').hidden=false;$('overlayActions').querySelector('button')?.focus({preventScroll:true});}
function closeOverlay(){$('overlay').hidden=true;}
function missionPreview(){const id=Number($('mission').value)||0,v=VERSES[id];$('missionVerse').textContent=v.text;$('record').textContent=saved.best[id]?`Personal best: ${saved.best[id].toLocaleString()}  ·  ${saved.medals[id]||'bronze'} medal`:'Your first sky rescue starts here.';}
VERSES.forEach((v,i)=>{const op=document.createElement('option');op.value=i;op.textContent=`${i+1}. ${v.name} · ${v.ref}`;$('mission').append(op);});
$('mission').value=Number.isInteger(saved.mission)&&saved.mission>=0&&saved.mission<VERSES.length?saved.mission:0;
$('difficulty').value=settings[saved.difficulty]?saved.difficulty:'normal';
$('mission').addEventListener('change',missionPreview);missionPreview();
function soundLabel(){$('soundBtn').textContent=saved.sound?'Sound on':'Sound off';$('soundBtn').setAttribute('aria-pressed',String(saved.sound));}soundLabel();
$('soundBtn').addEventListener('click',()=>{saved.sound=!saved.sound;save();soundLabel();if(saved.sound)initAudio();});
function begin(){initAudio();const mission=Number($('mission').value)||0,difficulty=$('difficulty').value,stage=Number($('startMode').value);saved.mission=mission;saved.difficulty=difficulty;save();run={mission,difficulty,stage,startStage:stage,words:tokens(VERSES[mission]),index:0,score:0,streak:0,bestStreak:0,charge:0,chargeMax:5,hearts:settings[difficulty].hearts,maxHearts:settings[difficulty].hearts,mistakes:0,hints:0,shield:0,slow:1,revealed:false,rescues:0,burstWords:0,elapsed:0,nearMiss:0};lane=laneVisual=1;particles=[];beams=[];rings=[];$('menu').hidden=true;$('hud').hidden=false;$('controls').hidden=false;$('target').hidden=false;document.body.classList.add('playing');startStage();}
$('playBtn').addEventListener('click',begin);
function startStage(){state='briefing';gate=null;hazards=[];run.index=0;run.revealed=false;run.charge=0;jumpTime=0;burstTime=0;invincible=0;updateHUD();const v=VERSES[run.mission];const title=['The sky needs you!','Now, from memory.','The storm engine!'][run.stage];const description=[
 'Ride into the next word. Swipe left or right, or tap its lane button. Swipe UP to jump coral hazards. Five correct words charge your burst!',
 'The rest of the verse is hidden. Choose each next word from memory. Need help? Reveal the word and keep flying.',
 'Every correct word fires a blast at the storm engine. Dodge its attacks, finish the verse, and free the sky!'
 ][run.stage];showOverlay(`ROUND ${run.stage+1} OF 3 · ${v.ref} KJV`,title,`<p>${description}</p><p class="quote">${v.text}</p>`,[{label:run.stage===2?'TAKE ON THE BOSS →':'READY TO FLY →',primary:true,fn:()=>{closeOverlay();state='playing';makeGate();notice(run.stage===0?'Steer into “'+clean(run.words[0])+'”':'You’ve got this!',1.8);}}]);}
function makeGate(){const c=choices(run.words,run.index);gate={...c,p:0,failed:false,delay:.3};run.revealed=false;hazards=[];const odds=settings[run.difficulty].hazard+(run.stage===2?.18:0);if(run.index>0&&Math.random()<odds){hazards.push({lane:Math.floor(Math.random()*3),p:.20,done:false});}if(run.stage===2&&run.index>3&&Math.random()<.35){const used=hazards[0]?.lane;hazards.push({lane:[0,1,2].filter(x=>x!==used)[Math.floor(Math.random()*(used===undefined?3:2))],p:.04,done:false});}updateHUD();}
function updateHUD(){if(!run)return;const v=VERSES[run.mission];setText($('stageLabel'),`${run.stage+1}/3 · ${['LEARN','RECALL','BOSS'][run.stage]}`);setText($('health'),'♥'.repeat(Math.max(0,run.hearts))+'♡'.repeat(Math.max(0,run.maxHearts-run.hearts)));setText($('score'),run.score.toLocaleString());setText($('combo'),`×${multiplier(run.streak)} · ${run.streak} streak`);setText($('reference'),`${v.ref} KJV`);setText($('wordCount'),`${run.index}/${run.words.length}`);setText($('charge'),`${run.charge}/${run.chargeMax}`);$('burstBtn').classList.toggle('ready',run.charge>=run.chargeMax);$('bossHud').hidden=run.stage!==2;$('bossBar').value=100*(1-run.index/run.words.length);$('hintBtn').disabled=run.stage===0||run.revealed;const fragment=document.createDocumentFragment();run.words.forEach((w,i)=>{const span=document.createElement('span');span.className=i<run.index?'done':i===run.index&&(run.stage===0||run.revealed)?'current':run.stage>0?'masked':'';span.textContent=(i<run.index||run.stage===0||run.revealed&&i===run.index?w:'•'.repeat(Math.min(clean(w).length,7)))+' ';fragment.append(span);});$('verse').replaceChildren(fragment);setText($('targetLabel'),run.stage===0||run.revealed?'NEXT WORD':'WHAT COMES NEXT?');setText($('targetWord'),run.index>=run.words.length?'COMPLETE':run.stage===0||run.revealed?clean(run.words[run.index]):run.index?`“${clean(run.words[run.index-1])} …”`:'Start the verse');laneButtons.forEach((b,i)=>{b.textContent=gate?gate.options[i]:['←','•','→'][i];b.classList.toggle('selected',lane===i);b.classList.toggle('correct',Boolean(gate&&(run.stage===0||run.revealed)&&gate.correct===i));});fitHUD();}
function steer(next){if(state!=='playing')return;const previous=lane;lane=Math.max(0,Math.min(2,next));if(lane!==previous)sound('move');laneButtons.forEach((b,i)=>b.classList.toggle('selected',i===lane));}
function jump(){if(state!=='playing'||jumpTime>0)return;jumpTime=.83;sound('jump');emit(playerPosition().x,playerPosition().y,'#c0fff3',10,.55);}
function burst(){if(state!=='playing')return;if(run.charge<run.chargeMax){notice(`Charge burst: ${run.charge}/${run.chargeMax} words`,1);return;}run.charge=0;burstTime=4;run.burstWords=3;invincible=4;hazards.forEach(h=>{const p=project(h.lane,h.p);emit(p.x,p.y,'#75ffce',20,1.5);});hazards=[];rings.push({x:playerPosition().x,y:playerPosition().y,r:15,life:1});sound('burst');notice('SKY BURST! Shield + 3 double-score words',1.9);updateHUD();}
function reveal(){if(state!=='playing'||run.stage===0||run.revealed)return;run.revealed=true;run.hints++;gate.delay=Math.max(gate.delay,1.2);notice(`Next word: ${clean(run.words[run.index])}`,1.5);updateHUD();}
$('jumpBtn').addEventListener('click',jump);$('burstBtn').addEventListener('click',burst);$('hintBtn').addEventListener('click',reveal);laneButtons.forEach(b=>b.addEventListener('click',()=>steer(Number(b.dataset.lane))));
let pointer=null;
canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const dx=e.clientX-pointer.lastX,dy=e.clientY-pointer.lastY;if(Math.max(Math.abs(dx),Math.abs(dy))<25)return;pointer.moved=true;if(Math.abs(dx)>Math.abs(dy)){steer(lane+Math.sign(dx));}else if(dy<0)jump();else burst();pointer.lastX=e.clientX;pointer.lastY=e.clientY;});
canvas.addEventListener('pointerup',e=>{if(pointer&&pointer.id===e.pointerId&&!pointer.moved)steer(Math.min(2,Math.floor((e.clientX-canvas.getBoundingClientRect().left)/width*3)));pointer=null;});canvas.addEventListener('pointercancel',()=>pointer=null);
addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Escape'].includes(e.key))e.preventDefault();if(e.repeat)return;if(e.key==='Escape'){togglePause();return;}if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')steer(lane-1);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')steer(lane+1);if(e.key==='ArrowUp'||e.key===' '||e.key.toLowerCase()==='w')jump();if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')burst();if(e.key.toLowerCase()==='h')reveal();});
function toMenu(){state='menu';run=null;gate=null;hazards=[];closeOverlay();$('menu').hidden=false;$('hud').hidden=true;$('controls').hidden=true;$('target').hidden=true;$('announcement').classList.remove('visible');document.body.classList.remove('playing');missionPreview();$('playBtn').focus({preventScroll:true});}
function pause(){if(state!=='playing')return;state='paused';showOverlay('TAKE A BREATHER','Flight paused',`<p>Your place in the verse is saved for this flight.</p><p>Swipe ← → to steer. Swipe ↑ to jump. Swipe ↓ for a charged burst.</p>`,[{label:'KEEP FLYING →',primary:true,fn:resume},{label:saved.sound?'Turn sound off':'Turn sound on',fn:()=>{saved.sound=!saved.sound;save();soundLabel();if(saved.sound)initAudio();resume();}},{label:'Restart this mission',fn:begin},{label:'Choose another mission',fn:toMenu}]);}
function resume(){if(state!=='paused')return;closeOverlay();state='playing';initAudio();}
function togglePause(){if(state==='playing')pause();else if(state==='paused')resume();}
$('pauseBtn').addEventListener('click',togglePause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});addEventListener('blur',()=>{pointer=null;pause();});
function damage(reason){if(state!=='playing')return;if(reason==='hazard'&&(invincible>0||run.shield>0)){if(invincible<=0)run.shield--;notice('Shield blocked it!',.8);sound('correct');return;}run.hearts--;run.mistakes++;run.streak=0;screenShake=reduced?0:.35;if(reason==='hazard')invincible=1.4;sound('hit');emit(playerPosition().x,playerPosition().y,'#ff7e99',25);if(reason==='hazard')notice('Ouch! Swipe up to jump',1.3);updateHUD();if(run.hearts<=0){state='down';hazards=[];showOverlay('DON’T GIVE UP','Ready for a rescue?',`<p>You reached word <b>${run.index+1} of ${run.words.length}</b>. Try again from this word with full hearts. Your score stays; your medal reflects the retries.</p>`,[{label:'RESCUE ME — KEEP GOING →',primary:true,fn:()=>{run.hearts=run.maxHearts;run.rescues++;run.charge=0;gate.p=.12;gate.delay=1;invincible=2;closeOverlay();state='playing';updateHUD();}},{label:'Start a fresh run',fn:begin},{label:'Back to missions',fn:toMenu}]);}}
function collect(){if(!gate||state!=='playing')return;if(lane!==gate.correct){run.revealed=true;gate.failed=true;gate.p=.46;gate.delay=1.1;hazards=[];notice(`Try “${clean(run.words[run.index])}” — same lane!`,2);damage('word');updateHUD();return;}const pos=project(gate.correct,.93);run.streak++;run.bestStreak=Math.max(run.bestStreak,run.streak);const boosted=run.burstWords>0;run.score+=100*multiplier(run.streak)*(boosted?2:1);if(boosted)run.burstWords--;run.charge=Math.min(run.chargeMax,run.charge+1);emit(pos.x,pos.y,boosted?'#ffffff':'#75ffce',24,1.25);sound('correct');if(run.stage===2){beams.push({x:pos.x,y:pos.y,life:.45});screenShake=reduced?0:.08;}run.index++;if(run.index===run.words.length){run.score+=500*(run.stage+1);gate=null;hazards=[];updateHUD();endStage();return;}if(run.streak%4===0){notice(`${run.streak} WORD COMBO! ×${multiplier(run.streak)}`,1.2);rings.push({x:pos.x,y:pos.y,r:5,life:.6});}else if(run.charge===run.chargeMax)notice('BURST READY! Swipe down ↓',1.2);makeGate();}
function endStage(){state='reward';sound('win');for(let i=0;i<4;i++)emit(width*(.2+Math.random()*.6),height*(.35+Math.random()*.3),'#ffe49a',30);if(run.stage===2){finish();return;}const v=VERSES[run.mission];const title=run.stage===0?'Route restored!':'Storm gate unlocked!';const upgrades=upgradeDefs.filter(u=>u.id!=='charge'||run.chargeMax>3).slice();showOverlay('PICK YOUR POWER-UP',title,`<p class="quote">${v.text}</p><p>Choose a flight upgrade. Then ${run.stage===0?'try the verse from memory':'take on the storm engine'}.</p>`,upgrades.map(u=>({label:u.title,desc:u.desc,fn:()=>{if(u.id==='heart'){run.maxHearts=Math.min(7,run.maxHearts+1);run.hearts=run.maxHearts;}if(u.id==='shield')run.shield+=2;if(u.id==='slow')run.slow*=1.25;if(u.id==='charge')run.chargeMax=3;run.stage++;run.hearts=Math.min(run.maxHearts,run.hearts+1);startStage();}})));}
function finish(){state='complete';const rating=medal(run.mistakes+run.rescues*3,run.hints),ranks={bronze:1,silver:2,gold:3};run.score+=run.hearts*100;const best=saved.best[run.mission]||0;const newBest=run.score>best;saved.best[run.mission]=Math.max(best,run.score);if((ranks[saved.medals[run.mission]]||0)<ranks[rating])saved.medals[run.mission]=rating;save();const v=VERSES[run.mission];showOverlay('SKY RESCUE COMPLETE','You broke the storm!',`<div class="medal">${{gold:'🥇',silver:'🥈',bronze:'🥉'}[rating]}</div><p>${rating.toUpperCase()} MEDAL · ${v.ref} KJV${newBest?' · NEW PERSONAL BEST!':''}</p><div class="resultstats"><div><strong>${run.score.toLocaleString()}</strong><span>SCORE</span></div><div><strong>${run.bestStreak}</strong><span>BEST STREAK</span></div><div><strong>${run.hints}</strong><span>HINTS</span></div></div><p class="quote">${v.text}</p><p>${run.startStage===0?'You read it, recalled it, and used it to win.':'Challenge complete. Try the full Learn → Recall → Boss journey too!'} Can you say the whole verse aloud now?</p>`,[{label:'NEXT SKY MISSION →',primary:true,fn:()=>{$('mission').value=(run.mission+1)%VERSES.length;$('startMode').value='0';begin();}},{label:'Replay this mission',fn:begin},{label:'Copy my score challenge',fn:async()=>{const message=`I scored ${run.score.toLocaleString()} in Hide the Word: Skybreak (${v.ref} KJV)! Can you beat my ${run.bestStreak}-word streak? https://tharderer.github.io/voice-recognition-test/skybreak/`;try{await navigator.clipboard.writeText(message);notice('Score challenge copied!',2);}catch{showOverlay('YOUR SCORE CHALLENGE','Copy and challenge a friend',`<p>${message}</p>`,[{label:'Back to results',fn:finishResults}]);}}},{label:'Back to missions',fn:toMenu}]);}
function finishResults(){// Reopen without awarding the completion bonus twice.
run.score-=run.hearts*100;finish();}
function layout(){const landscape=width>height&&height<600;return {horizon:Math.min(height*.61,Math.max(trackHorizon,height*(landscape?.43:.40))),bottom:height*(landscape?.78:.79),spread:Math.min(width*.34,330)};}
function project(l,p){const L=layout(),depth=Math.max(0,p);return {x:width/2+(l-1)*L.spread*(.55+depth*.45),y:L.horizon+(L.bottom-L.horizon)*Math.pow(depth,1.42),s:.28+depth*.78};}
function playerPosition(){const p=project(laneVisual,.95);p.y-=jumpTime>0?Math.sin(Math.PI*(1-jumpTime/.83))*Math.min(height*.17,88):0;return p;}
function rounded(x,y,w,h,r,color,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(color){ctx.fillStyle=color;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function polygon(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function ellipse(x,y,rx,ry,color){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function drawBackground(){const grad=ctx.createLinearGradient(0,0,0,height);grad.addColorStop(0,'#20284e');grad.addColorStop(.45,'#25496b');grad.addColorStop(1,'#0b1935');ctx.fillStyle=grad;ctx.fillRect(0,0,width,height);if(scenery.complete&&scenery.naturalWidth){const scale=Math.max(width/scenery.width,height/scenery.height),w=scenery.width*scale,h=scenery.height*scale;ctx.globalAlpha=.83;ctx.drawImage(scenery,(width-w)/2,(height-h)/2,w,h);ctx.globalAlpha=1;const shade=ctx.createLinearGradient(0,0,0,height);shade.addColorStop(0,'#08122b30');shade.addColorStop(.45,'#101b3510');shade.addColorStop(1,'#0a1739b5');ctx.fillStyle=shade;ctx.fillRect(0,0,width,height);}for(const star of starfield){const y=(star.y*height+clock*star.s*9)%height;ctx.globalAlpha=.25+Math.sin(clock+star.x*9)*.18;ctx.fillStyle='#d2fff1';ctx.fillRect(star.x*width,y,star.s,star.s*2);}ctx.globalAlpha=1;}
function drawRoad(){const L=layout();for(let l=0;l<3;l++){const a=project(l,0),b=project(l,1.3),halfTop=L.spread*.085,halfBottom=L.spread*.43;polygon([[a.x-halfTop,a.y],[a.x+halfTop,a.y],[b.x+halfBottom,b.y],[b.x-halfBottom,b.y]],l===lane?'#409ca02d':'#30516b26');ctx.strokeStyle=l===lane?'#75ffce72':'#90c9ff32';ctx.lineWidth=l===lane?2:1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}for(let i=0;i<16;i++){const p=((i/16+clock*(burstTime>0?.45:.18))%1)*1.2;const a=project(-.43,p),b=project(2.43,p);ctx.globalAlpha=p*.25;ctx.strokeStyle='#a4edff';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}ctx.globalAlpha=1;}
function drawBoss(){if(!run||run.stage!==2)return;const L=layout(),x=width/2,y=L.horizon-8+Math.sin(clock*1.7)*5,s=Math.min(width/420,height/570,1.15);ctx.save();ctx.translate(x,y);ctx.scale(s,s);const health=1-run.index/run.words.length;ctx.rotate(Math.sin(clock)*.05);ellipse(0,0,95,22,'#0a16374d');for(let i=0;i<6;i++){ctx.save();ctx.rotate(clock*.3+i*Math.PI/3);polygon([[25,-10],[58,-15],[83,0],[58,15],[25,10]],i%2?'#465078':'#68799c','#94bad3');ctx.restore();}ellipse(0,0,37,37,'#172644');ellipse(0,0,29,29,health<.3?'#ffb176':'#ff789c');ellipse(0,0,21+Math.sin(clock*8)*3,21+Math.sin(clock*8)*3,'#512859');polygon([[-9,-12],[11,0],[-9,12]],'#ffe1ac');ctx.restore();}
function drawGate(){if(!gate||!run)return;for(let l=0;l<3;l++){const pos=project(l,gate.p),s=pos.s;const available=Math.min(width/3-12,180);const w=Math.min(available,layout().spread*(.55+gate.p*.45)*.89),h=45*s+12;const highlight=(run.stage===0||run.revealed)&&l===gate.correct;const color=highlight?'#ffe49a':l===lane?'#75ffce':'#d8eaff';ctx.save();ctx.translate(pos.x,pos.y);ellipse(0,h*.7,w*.46,10*s,'#091b4160');ctx.shadowBlur=reduced?0:highlight?22:10;ctx.shadowColor=color;ctx.lineWidth=highlight?3:2;rounded(-w/2,-h/2,w,h,10*s,'#152e50ed',color);ctx.shadowBlur=0;ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';let fs=Math.min(24,Math.max(15,20*s));ctx.font=`900 ${fs}px "Trebuchet MS", sans-serif`;while(ctx.measureText(gate.options[l]).width>w-12&&fs>8){fs--;ctx.font=`900 ${fs}px "Trebuchet MS", sans-serif`;}ctx.fillText(gate.options[l],0,0);ctx.restore();}}
function drawHazard(h){if(h.done)return;const p=project(h.lane,h.p),s=p.s*1.1,r=20*s;ctx.save();ctx.translate(p.x,p.y);ellipse(0,r*.85,r*1.5,r*.3,'#070f3180');ctx.rotate(Math.sin(clock*6+h.lane)*.13);ctx.shadowColor='#ff6489';ctx.shadowBlur=reduced?0:16;polygon([[-r,0],[-r*.55,-r*.8],[0,-r*.25],[r*.5,-r*1.1],[r,r*.2],[0,r*.7]],'#ff6489','#ffc69e');ctx.shadowBlur=0;polygon([[-r*.2,-r*.1],[r*.5,-r*1.1],[r*.6,r*.3]],'#ffb18c');ctx.restore();if(h.p<.55){const end=project(h.lane,.95);ctx.save();ctx.setLineDash([5,8]);ctx.strokeStyle='#ff8d9c65';ctx.beginPath();ctx.moveTo(p.x,p.y+15);ctx.lineTo(end.x,end.y);ctx.stroke();ctx.restore();}}
function drawGlider(){const p=playerPosition(),ground=project(laneVisual,.95),scale=Math.min(1.15,Math.max(.78,width/550));ctx.save();ellipse(ground.x,ground.y+24,37*scale,9*scale,'#06163290');ctx.translate(p.x,p.y);ctx.scale(scale,scale);ctx.rotate((lane-laneVisual)*.20);if(invincible>0||run?.shield>0){ctx.strokeStyle='#75ffce';ctx.lineWidth=2;ctx.globalAlpha=.55+Math.sin(clock*9)*.15;ctx.beginPath();ctx.ellipse(0,0,48,44,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}if(invincible>0&&burstTime<=0)ctx.globalAlpha=.6+Math.sin(clock*20)*.3;const flame=14+Math.sin(clock*28)*6+(burstTime>0?28:0);polygon([[-9,17],[0,28+flame],[9,17]],'#72fbd4');polygon([[-5,18],[0,22+flame*.8],[5,18]],'#fff4b5');polygon([[-9,-12],[-48,17],[-23,20],[0,9],[23,20],[48,17],[9,-12]],'#7bd8d9','#d8fff3');polygon([[-9,-12],[-40,15],[-24,9],[-3,-18]],'#ffe2a1');polygon([[9,-12],[40,15],[24,9],[3,-18]],'#ffbd83');polygon([[0,-28],[-13,0],[-9,20],[9,20],[13,0]],'#f1f6e8','#b5f5ef');ellipse(0,-6,8,11,'#203f68');ellipse(-2,-9,3,5,'#85e6ea');ctx.restore();if(state==='playing'&&!reduced&&Math.random()<.45){particles.push({x:p.x+(Math.random()-.5)*15,y:p.y+28,vx:(Math.random()-.5)*20,vy:90+Math.random()*50,life:.3,max:.3,color:burstTime>0?'#ffe49a':'#75ffce',size:3});}}
function drawEffects(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=50*dt;if(p.life<=0){particles.splice(i,1);continue;}ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);}ctx.globalAlpha=1;for(let i=beams.length-1;i>=0;i--){const b=beams[i];b.life-=dt;if(b.life<=0){beams.splice(i,1);continue;}ctx.strokeStyle='#fff2ae';ctx.lineWidth=5*b.life/.45;ctx.shadowBlur=20;ctx.shadowColor='#ffce78';ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(width/2,layout().horizon-8);ctx.stroke();ctx.shadowBlur=0;}for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.life-=dt;r.r+=550*dt;if(r.life<=0){rings.splice(i,1);continue;}ctx.globalAlpha=r.life;ctx.strokeStyle='#a5fff2';ctx.lineWidth=5;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}}
function update(dt){laneVisual+=(lane-laneVisual)*Math.min(1,dt*17);jumpTime=Math.max(0,jumpTime-dt);invincible=Math.max(0,invincible-dt);burstTime=Math.max(0,burstTime-dt);screenShake=Math.max(0,screenShake-dt);run.elapsed+=dt;soundtrack(dt);if(!gate)return;if(gate.delay>0){gate.delay-=dt;return;}const travel=settings[run.difficulty].time*run.slow*(run.stage===0?1.05:run.stage===1?1:.94);const velocity=dt/travel*(burstTime>0?.77:1);gate.p+=velocity;for(const h of hazards){if(h.done)continue;h.p+=velocity*1.09;if(h.p>=.92){h.done=true;if(h.lane===lane){if(jumpTime>.13){run.score+=75;run.nearMiss++;emit(project(lane,.95).x,project(lane,.95).y,'#ffe49a',14);notice('CLEAN JUMP! +75',.7);sound('correct');updateHUD();}else damage('hazard');}else if(Math.abs(h.lane-lane)===1&&h.p<.97){run.score+=15;updateHUD();}}if(state!=='playing')return;}if(gate.p>=.96)collect();}
function frame(t){const dt=Math.min(.04,(t-last)/1000||.016);last=t;const active=state==='playing';if(state==='menu'||active||state==='complete'||state==='reward')clock+=dt;if(active)update(dt);if(noticeTime>0){noticeTime-=dt;if(noticeTime<=0)$('announcement').classList.remove('visible');}ctx.save();if(active&&screenShake>0&&!reduced)ctx.translate((Math.random()-.5)*screenShake*14,(Math.random()-.5)*screenShake*14);drawBackground();drawRoad();drawBoss();if(gate){const objects=[{p:gate.p,kind:'gate'},...hazards.filter(h=>!h.done).map(h=>({p:h.p,kind:'hazard',h}))].sort((a,b)=>a.p-b.p);for(const o of objects)o.kind==='gate'?drawGate():drawHazard(o.h);}drawGlider();drawEffects(state==='paused'?0:dt);ctx.restore();requestAnimationFrame(frame);}
requestAnimationFrame(frame);
})();
