/* Endless 256 gameplay layer for Verse Chomper Royale. */
(function(){
"use strict";
const COLS=27,ROWS=301,START_ROW=297,START_COL=13,BASE_SPEED=5.1,BASE_GHOSTS=3;
const DECOYS=["some","many","people","always","were","unto","through","great","good","world","every","grace","shall","because","before","heaven","works","their","truth","faith","heart","word"];
const irand=(r,m)=>Math.floor(r()*m),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),cellKey=(x,y)=>x+","+y;
function buildEndlessMaze(seed){const rand=mulberry32((seed||1)>>>0),g=Array.from({length:ROWS},()=>Array(COLS).fill(1));for(let r=1;r<ROWS-1;r++){if(r%2===1){for(let c=1;c<COLS-1;c++)g[r][c]=0}else{const picks=[];const count=4+irand(rand,3);while(picks.length<count){let c=1+2*irand(rand,Math.floor((COLS-1)/2));if(c>=COLS-1)c=COLS-2;if(!picks.includes(c))picks.push(c)}if(r>START_ROW-6&&!picks.includes(START_COL))picks.push(START_COL);picks.forEach(c=>g[r][c]=0)}}for(let r=279;r>20;r-=34){for(let y=r-2;y<=r+2;y++){if(y<=0||y>=ROWS-1)continue;for(let x=5;x<=21;x++)g[y][x]=0}g[r][1]=0;g[r][COLS-2]=0}g[START_ROW][START_COL]=0;g[START_ROW-1][START_COL]=0;return g}
function nearestOpenRow(r){r=clamp(Math.round(r),1,ROWS-2);if(r%2===0)r--;return r}
function openAt(x,y){x=Math.floor(x);y=Math.floor(y);return !!game&&y>=0&&y<game.maze.length&&x>=0&&x<game.maze[0].length&&game.maze[y][x]===0}
function randomAhead(minRows,maxRows,occupied=[]){const rand=game.rand||Math.random;for(let i=0;i<160;i++){const row=nearestOpenRow(game.player.y-(minRows+irand(rand,Math.max(1,maxRows-minRows+1)))),col=1+irand(rand,COLS-2);if(!openAt(col,row))continue;if(occupied.some(p=>Math.abs(p.x-col)+Math.abs(p.y-row)<2))continue;return{x:col,y:row}}return{x:START_COL,y:nearestOpenRow(game.player.y-minRows)}}
function resetPlayerAt(row){row=nearestOpenRow(row);let col=START_COL;if(!openAt(col,row)){for(let d=1;d<COLS;d++){if(openAt(START_COL-d,row)){col=START_COL-d;break}if(openAt(START_COL+d,row)){col=START_COL+d;break}}}game.player={x:col+.5,y:row+.5,dir:"",nextDir:"",want:"",speed:BASE_SPEED,lastCenter:"",lastDot:""}}
startGame=function(seed){session.phase="game";showScreen(els.game);const words=verseWords(session.verseKey),rand=mulberry32((seed||1)>>>0);game={seed,rand,maze:buildEndlessMaze(seed),words,progress:0,running:false,player:null,ghosts:[],wordChoices:[],powerPellets:[],dots:new Set(),score:0,combo:0,powerCount:0,powerUntil:0,lives:3,frozenUntil:0,respawnUntil:0,reverseUntil:0,tunnelBlockedUntil:0,ghostRushUntil:0,extraGhostUntil:0,lastPowerAt:0,startedAt:performance.now(),glitchRow:ROWS-1,glitchStartedAt:performance.now(),cameraTop:START_ROW-10,visibleRows:14,tile:1,farthestRow:START_ROW,distance:0};resetPlayerAt(START_ROW);refillGhosts();buildWordChoices();spawnPowerPellets();resizeRoyaleCanvas();updateVerseUI();updateLivesUI();renderOpponents();updateEndlessStats();countdownToStart();if(!animationStarted){animationStarted=true;lastFrame=performance.now();requestAnimationFrame(frame)}};
walkableCells=function(){if(!game)return[];const cells=[],minY=Math.max(1,Math.floor(game.player.y-14)),maxY=Math.min(ROWS-2,Math.floor(game.player.y+3));for(let y=minY;y<=maxY;y++)for(let x=1;x<COLS-1;x++)if(game.maze[y][x]===0)cells.push({x,y});return cells};
buildWordChoices=function(){if(!game||game.progress>=game.words.length){if(game)game.wordChoices=[];return}const current=game.words[game.progress],pool=game.words.filter((w,i)=>i!==game.progress&&w.normalized!==current.normalized).concat(DECOYS.map(w=>({display:w,normalized:normalizeWord(w)}))),unique=[],seen=new Set([current.normalized]);shuffle(pool,game.rand);for(const w of pool){if(!w.normalized||seen.has(w.normalized))continue;seen.add(w.normalized);unique.push(w);if(unique.length===4)break}const choices=[{...current,correct:true},...unique.map(w=>({...w,correct:false}))];shuffle(choices,game.rand);const used=[];game.wordChoices=choices.map(choice=>{const p=randomAhead(3,10,used);used.push(p);return{...choice,x:p.x,y:p.y}})};
spawnPowerPellets=function(){if(!game)return;game.powerPellets=[];for(let i=0;i<3;i++){const p=randomAhead(5+i*3,13+i*4,game.wordChoices.concat(game.powerPellets));game.powerPellets.push({x:p.x,y:p.y,active:true,respawnAt:0})}};
function spawnGhost(type,row,bonus=false){row=nearestOpenRow(row);let p=randomAhead(Math.max(3,Math.round(game.player.y-row-2)),Math.max(5,Math.round(game.player.y-row+2)),game.ghosts);p.y=row;if(!openAt(p.x,p.y)){for(let x=1;x<COLS-1;x++)if(openAt(x,p.y)){p.x=x;break}}const idx=game.ghosts.length;game.ghosts.push({type,x:p.x+.5,y:p.y+.5,dir:game.rand()<.5?"left":"right",lastCenter:"",speed:type==="chaser"?2.5:type==="ambush"?2.3:2.08,color:GHOST_COLORS[idx%GHOST_COLORS.length],bonus})}
function refillGhosts(){if(!game)return;game.ghosts=game.ghosts.filter(g=>g.bonus||(g.y<game.player.y+14&&g.y>game.player.y-24));const normal=game.ghosts.filter(g=>!g.bonus),types=["chaser","patrol","ambush"];while(normal.length<BASE_GHOSTS){const type=types[normal.length%types.length];spawnGhost(type,game.player.y-(7+normal.length*5+irand(game.rand,4)));normal.push(game.ghosts[game.ghosts.length-1])}}
canMove=function(entity,dir){if(!game||!dir||!DIRS[dir])return false;const d=DIRS[dir],cx=Math.floor(entity.x),cy=Math.floor(entity.y);return openAt(cx+d.x,cy+d.y)};handleTunnel=function(){};
setDirection=function(dir){if(!game||!DIRS[dir])return;const p=game.player;p.nextDir=dir;p.want=dir;if(p.dir&&OPPOSITE[p.dir]===dir){p.dir=dir;p.lastCenter=""}};
function collectDotAtCenter(){const p=game.player,c=Math.floor(p.x),r=Math.floor(p.y),k=cellKey(c,r);if(p.lastDot===k)return;p.lastDot=k;if(!game.dots.has(k)){game.dots.add(k);game.combo++;game.score++;if([16,32,64,128,256].includes(game.combo)){game.score+=game.combo;showEffect(game.combo+" DOT COMBO!",false)}}}
movePlayer=function(dt,now){const p=game.player,cx=Math.floor(p.x)+.5,cy=Math.floor(p.y)+.5,near=Math.abs(p.x-cx)<.12&&Math.abs(p.y-cy)<.12,k=Math.floor(p.x)+","+Math.floor(p.y),stopped=!p.dir||!DIRS[p.dir];if(near&&(p.lastCenter!==k||stopped)){p.x=cx;p.y=cy;collectDotAtCenter();let wanted=p.want||p.nextDir;if(now<game.reverseUntil&&wanted)wanted=OPPOSITE[wanted];if(wanted&&canMove(p,wanted))p.dir=wanted;if(!p.dir||!canMove(p,p.dir))p.dir="";p.lastCenter=k}if(!p.dir||!DIRS[p.dir])return;const d=DIRS[p.dir];p.x+=d.x*BASE_SPEED*dt;p.y+=d.y*BASE_SPEED*dt;game.farthestRow=Math.min(game.farthestRow,p.y);game.distance=Math.max(game.distance,START_ROW-game.farthestRow)};
function ghostTarget(g){if(g.type==="ambush"){const d=DIRS[game.player.dir]||{x:0,y:0};return{x:game.player.x+d.x*4,y:game.player.y+d.y*4}}if(g.type==="patrol")return{x:game.player.x,y:g.y};return{x:game.player.x,y:game.player.y}}
ghostDirScore=function(g,dir){const d=DIRS[dir],t=ghostTarget(g);return Math.abs(g.x+d.x-t.x)+Math.abs(g.y+d.y-t.y)+game.rand()*1.8};
updateGhosts=function(dt,now){for(const g of game.ghosts){const cx=Math.floor(g.x)+.5,cy=Math.floor(g.y)+.5,near=Math.abs(g.x-cx)<.12&&Math.abs(g.y-cy)<.12,k=Math.floor(g.x)+","+Math.floor(g.y);if(near&&g.lastCenter!==k){g.x=cx;g.y=cy;let opts=Object.keys(DIRS).filter(dir=>canMove(g,dir)),nr=opts.filter(dir=>!g.dir||dir!==OPPOSITE[g.dir]);if(nr.length)opts=nr;if(opts.length){opts.sort((a,b)=>ghostDirScore(g,a)-ghostDirScore(g,b));g.dir=game.rand()<.78?opts[0]:opts[irand(game.rand,opts.length)]}else g.dir="";g.lastCenter=k}if(!g.dir||!DIRS[g.dir])continue;const d=DIRS[g.dir],rush=now<game.ghostRushUntil?1.6:1,scared=now<game.powerUntil?.72:1;g.x+=d.x*g.speed*rush*scared*dt;g.y+=d.y*g.speed*rush*scared*dt}};
checkWordCollisions=function(){for(const choice of game.wordChoices){if(Math.hypot(game.player.x-(choice.x+.5),game.player.y-(choice.y+.5))>=.55)continue;game.wordChoices=game.wordChoices.filter(c=>c!==choice);if(choice.correct){game.score+=100+Math.min(game.combo,100);game.powerCount++;if(game.powerCount>=4){game.powerCount=0;game.powerUntil=performance.now()+8500;send("power");showEffect("VERSE POWER! GHOSTS ARE EDIBLE",false)}}else game.combo=0;send("word",{word:choice.normalized});if(!choice.correct)setTimeout(()=>{if(game&&session.phase==="game")buildWordChoices()},180);updateEndlessStats();break}};
checkPowerPellets=function(now){for(const p of game.powerPellets){if(!p.active)continue;if(Math.hypot(game.player.x-(p.x+.5),game.player.y-(p.y+.5))<.52){p.active=false;p.respawnAt=now+12000;game.powerUntil=Math.max(game.powerUntil,now+6500);game.score+=75;showEffect("POWER PELLET!",false);break}}};
applyWrongWordPenalty=function(){if(!game)return;game.combo=0;game.score=Math.max(0,game.score-10);showEffect("WRONG WORD — COMBO BROKEN",true);updateEndlessStats()};
checkGhostCollision=function(now){if(now<game.respawnUntil)return;const hit=game.ghosts.find(g=>Math.hypot(game.player.x-g.x,game.player.y-g.y)<.58);if(!hit)return;if(now<game.powerUntil){game.score+=200;hit.y=nearestOpenRow(game.player.y-16)+.5;hit.x=(3+2*irand(game.rand,11))+.5;hit.lastCenter="";showEffect("GHOST CHOMP +200",false);return}game.respawnUntil=now+1700;game.combo=0;send("death");showEffect("GHOST GOT YOU",true);const safe=nearestOpenRow(game.player.y-5);setTimeout(()=>{if(!game||session.phase!=="game")return;resetPlayerAt(safe);game.glitchRow=Math.max(game.glitchRow,game.player.y+10);game.ghosts=[];refillGhosts();buildWordChoices();updateLivesUI();updateEndlessStats()},500)};
function checkGlitch(now,dt){if(now-game.glitchStartedAt>2100)game.glitchRow-=dt*(.34+Math.min(.26,(game.progress/Math.max(1,game.words.length))*.22));if(game.player.y>game.glitchRow-.35&&now>=game.respawnUntil){game.respawnUntil=now+1700;game.combo=0;send("death");showEffect("THE GLITCH CAUGHT YOU",true);const safe=nearestOpenRow(game.player.y-7);setTimeout(()=>{if(!game||session.phase!=="game")return;resetPlayerAt(safe);game.glitchRow=Math.max(game.glitchRow,game.player.y+11);game.ghosts=[];refillGhosts();buildWordChoices()},500)}}
updateGame=function(dt,now){if(now>=game.respawnUntil&&now>=game.frozenUntil)movePlayer(dt,now);updateGhosts(dt,now);checkWordCollisions();checkPowerPellets(now);checkGhostCollision(now);for(const p of game.powerPellets)if(!p.active&&now>=p.respawnAt){const n=randomAhead(6,16,game.wordChoices.concat(game.powerPellets));p.x=n.x;p.y=n.y;p.active=true}game.wordChoices=game.wordChoices.filter(w=>w.y<game.player.y+4&&w.y>game.player.y-20);const correct=game.wordChoices.find(w=>w.correct);if(game.progress<game.words.length&&(!correct||correct.y>game.player.y+1))buildWordChoices();if(game.extraGhostUntil&&now>game.extraGhostUntil){game.ghosts=game.ghosts.filter(g=>!g.bonus);game.extraGhostUntil=0}refillGhosts();checkGlitch(now,dt);game.cameraTop=clamp(game.player.y-game.visibleRows*.68,0,ROWS-game.visibleRows);updateEndlessStats()};
attackName=function(type){return({extraGhost:"EXTRA GHOST",ghostRush:"GHOST RUSH",reverse:"REVERSE CONTROLS",glitchSurge:"GLITCH SURGE"})[type]||"ATTACK"};ATTACKS.splice(0,ATTACKS.length,"extraGhost","ghostRush","reverse","glitchSurge");
applyAttack=function(type,fromName="Rival"){if(!game)return;const now=performance.now();if(type==="extraGhost"){spawnGhost("chaser",game.player.y-9,true);game.extraGhostUntil=Math.max(game.extraGhostUntil,now+9000)}else if(type==="ghostRush")game.ghostRushUntil=Math.max(game.ghostRushUntil,now+6500);else if(type==="reverse")game.reverseUntil=Math.max(game.reverseUntil,now+4000);else if(type==="glitchSurge")game.glitchRow=Math.min(game.glitchRow,game.player.y+5.5);showEffect(fromName+": "+attackName(type)+"!",true)};
function resizeRoyaleCanvas(){if(!game)return;const rect=els.canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),cssW=Math.max(320,rect.width||window.innerWidth),cssH=Math.max(180,rect.height||Math.max(180,window.innerHeight-120));els.canvas.width=Math.round(cssW*dpr);els.canvas.height=Math.round(cssH*dpr);game.dpr=dpr;game.tile=els.canvas.width/COLS;game.visibleRows=els.canvas.height/game.tile;game.cameraTop=clamp(game.player.y-game.visibleRows*.68,0,ROWS-game.visibleRows)}
function drawWall(x,y,t){ctx.fillStyle="#111a4d";ctx.fillRect(x+t*.05,y+t*.05,t*.90,t*.90);ctx.fillStyle="#273b9b";ctx.fillRect(x+t*.10,y+t*.10,t*.80,t*.18);ctx.fillStyle="#0a102f";ctx.fillRect(x+t*.10,y+t*.72,t*.80,t*.18)}
function drawGlitch(now,tile){const y=(game.glitchRow-game.cameraTop)*tile;if(y>els.canvas.height)return;ctx.save();ctx.globalAlpha=.88;ctx.fillStyle="#5d1b73";ctx.fillRect(0,Math.max(0,y),els.canvas.width,els.canvas.height-Math.max(0,y));for(let i=0;i<45;i++){const yy=Math.max(0,y-12*game.dpr)+game.rand()*(els.canvas.height-Math.max(0,y)+20*game.dpr),xx=game.rand()*els.canvas.width;ctx.fillStyle=i%3===0?"#ff2ca8":i%3===1?"#36e6ff":"#783cff";ctx.globalAlpha=.18+game.rand()*.5;ctx.fillRect(xx,yy,(4+game.rand()*24)*game.dpr,(2+game.rand()*8)*game.dpr)}ctx.restore()}
drawGame=function(now){if(!game)return;const w=els.canvas.width,h=els.canvas.height,tile=game.tile||(w/COLS),start=Math.max(0,Math.floor(game.cameraTop)-1),end=Math.min(ROWS-1,Math.ceil(game.cameraTop+game.visibleRows)+1);ctx.fillStyle="#020309";ctx.fillRect(0,0,w,h);for(let r=start;r<=end;r++)for(let c=0;c<COLS;c++){const x=c*tile,y=(r-game.cameraTop)*tile;if(game.maze[r][c]===1)drawWall(x,y,tile);else if(!game.dots.has(cellKey(c,r))){ctx.fillStyle="#f4efc7";ctx.beginPath();ctx.arc(x+tile/2,y+tile/2,Math.max(1.3*game.dpr,tile*.052),0,Math.PI*2);ctx.fill()}}for(const choice of game.wordChoices){if(choice.y<start-1||choice.y>end+1)continue;const x=(choice.x+.5)*tile,y=(choice.y-game.cameraTop+.5)*tile,label=choice.display.replace(/[;:,.!?]$/g,""),fs=Math.max(10*game.dpr,tile*.31);ctx.font="900 "+fs+"px system-ui";const boxW=Math.max(tile*.9,ctx.measureText(label).width+12*game.dpr),boxH=tile*.57;ctx.fillStyle="#fff8d7";ctx.fillRect(x-boxW/2,y-boxH/2,boxW,boxH);ctx.strokeStyle=choice.correct?"#ffd94d":"#8ea0d4";ctx.lineWidth=1.5*game.dpr;ctx.strokeRect(x-boxW/2,y-boxH/2,boxW,boxH);ctx.fillStyle="#10131d";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(label,x,y)}for(const p of game.powerPellets){if(!p.active||p.y<start-1||p.y>end+1)continue;const x=(p.x+.5)*tile,y=(p.y-game.cameraTop+.5)*tile,rad=tile*(.18+.04*Math.sin(now/110));ctx.fillStyle="#fff";ctx.shadowBlur=10*game.dpr;ctx.shadowColor="#fff";ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}for(const g of game.ghosts){if(g.y<start-1||g.y>end+1)continue;drawGhost(g.x*tile,(g.y-game.cameraTop)*tile,tile*.31,now<game.powerUntil?"#315aff":g.color,now)}drawGlitch(now,tile);drawChomper(game.player.x*tile,(game.player.y-game.cameraTop)*tile,tile*.37,game.player.dir,now);if(now<game.respawnUntil){ctx.fillStyle="rgba(255,255,255,.10)";ctx.fillRect(0,0,w,h)}};
function updateEndlessStats(){if(!game)return;let s=document.getElementById("endlessStats");if(!s){s=document.createElement("div");s.id="endlessStats";s.className="endless-stats";document.querySelector(".canvas-wrap")?.appendChild(s)}const power=performance.now()<game.powerUntil?"ON":game.powerCount+"/4";s.innerHTML='<span>↑ <b>'+Math.floor(game.distance)+'</b></span><span>● <b>'+game.combo+'</b></span><span>★ <b>'+game.score+'</b></span><span>⚡ <b>'+power+'</b></span>'}
const oldHandleServerMessage=handleServerMessage;handleServerMessage=function(msg){const before=game?game.progress:0;oldHandleServerMessage(msg);if(game&&msg&&msg.type==="progress"&&msg.playerId===session.playerId&&game.progress>before)updateEndlessStats()};
window.addEventListener("resize",()=>{if(game&&session.phase==="game")setTimeout(resizeRoyaleCanvas,20)});window.addEventListener("orientationchange",()=>{if(game&&session.phase==="game")setTimeout(resizeRoyaleCanvas,250)});
const rules=document.querySelector(".rules-card p");if(rules)rules.innerHTML='Race upward through the <strong>endless maze</strong>. Chomp the KJV verse in order while ghosts and the rising glitch chase you. Every four correct words powers you up and launches trouble at a rival. First player to finish the verse wins.';const tagline=document.querySelector(".tagline");if(tagline)tagline.textContent="Same endless Verse Chomp mechanics — now racing live against 2–4 players.";
})();