(() => {
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),shell=document.getElementById('gameShell');
const objectiveEl=document.getElementById('objective'),progressEl=document.getElementById('progressText'),toastEl=document.getElementById('toast'),stonesEl=document.getElementById('stones');
const loading=document.getElementById('loading'),scripture=document.getElementById('scripture'),pause=document.getElementById('pause'),complete=document.getElementById('complete');
const menuBtn=document.getElementById('menuButton'),resumeBtn=document.getElementById('resumeButton'),restartBtn=document.getElementById('restartButton'),againBtn=document.getElementById('playAgainButton'),interactBtn=document.getElementById('interactButton'),continueBtn=document.getElementById('continueButton');
const zoomOutBtn=document.getElementById('zoomOutButton'),zoomInBtn=document.getElementById('zoomInButton'),zoomLevelEl=document.getElementById('zoomLevel');
const keys=new Set(),touchDirs=new Set();
let vw=960,vh=540,dpr=1,last=performance.now(),running=false,paused=true,world={w:3600,h:2200},cam={x:0,y:0},toastTimer=0,zoom=1;
const MIN_ZOOM=.6,MAX_ZOOM=1.6,ZOOM_STEP=.1;
const atlas=new Image();let atlasReady=false;
const SOURCE=1254,ATLAS=640,S=ATLAS/SOURCE;
const R={abramFront:[5,5,165,230],abramRight1:[170,5,160,235],abramRight2:[320,5,150,235],abramRight3:[460,5,155,235],abramRight4:[605,5,145,235],abramBack:[895,5,170,240],sarai:[10,245,85,175],lot:[360,245,85,175],servant:[680,245,80,175],girl:[918,245,82,175],sheep:[15,425,120,185],camel:[372,418,98,207],grain:[470,620,120,135],pack:[610,635,135,125],roll:[10,620,180,135],wall:[335,1115,145,130],gate:[835,930,410,185],palm:[690,915,165,225],well:[530,925,170,185],tent:[10,920,320,190],altar:[335,930,195,180],rock:[705,790,150,130],thorn:[560,790,145,130],cart:[845,790,180,130],guard:[10,750,80,170],campfire:[780,1120,140,125]};
const player={x:380,y:1810,r:24,speed:250,dir:'up',moving:false,anim:0};
let scene=[],walls=[],stones=[],followers=[],trail=[],state=null;
function freshState(){return{shechem:false,moreh:false,promise:false,stones:0,built:false,complete:false};}
function loadAtlas(){return new Promise(resolve=>{window.ABRAM_ATLAS_PARTS=[];let i=1;function next(){if(i>13){atlas.onload=()=>{atlasReady=true;resolve();};atlas.onerror=resolve;atlas.src='data:image/avif;base64,'+window.ABRAM_ATLAS_PARTS.join('');return;}const s=document.createElement('script');s.src=`../ab001-art/abram-avif-part${String(i).padStart(2,'0')}.js?v=3`;s.onload=()=>{i++;next();};s.onerror=()=>{i++;next();};document.head.appendChild(s);}next();});}
function sprite(name,x,y,w,alpha=1,flip=false){if(!atlasReady||!R[name])return;const r=R[name],h=w*(r[3]/r[2]);ctx.save();ctx.globalAlpha=alpha;if(flip){ctx.translate(x,0);ctx.scale(-1,1);ctx.translate(-x,0);}ctx.drawImage(atlas,r[0]*S,r[1]*S,r[2]*S,r[3]*S,x-w/2,y-h,w,h);ctx.restore();}
function addScene(img,x,y,w,z=0,flip=false){scene.push({img,x,y,w,z,flip});}function addWall(x,y,w,h){walls.push({x,y,w,h});}
function buildWorld(){scene=[];walls=[];stones=[];followers=[];trail=[];state=freshState();player.x=380;player.y=1810;player.dir='up';player.anim=0;
for(let x=120;x<3500;x+=145){addScene('wall',x,120,130);addScene('wall',x,2080,130)}for(let y=230;y<2030;y+=130){addScene('wall',115,y,120);addScene('wall',3490,y,120)}
[[330,1880,280],[660,1900,260]].forEach(([x,y,w])=>addScene('tent',x,y,w,1));addScene('campfire',510,1760,105,1);addScene('camel',610,1840,108,1);addScene('sheep',700,1900,75,1);addScene('sarai',460,1810,82,2);addScene('lot',540,1835,82,2);
[[300,1530],[620,1500],[1050,1690],[1300,1480],[1680,1770],[2050,1550],[2360,1800],[2760,1530],[3150,1750],[3270,1330],[2450,1320],[1780,1370],[980,1280],[480,1190],[1380,1150],[2150,1120],[3000,1080],[330,850],[800,850],[1330,820],[1800,760],[2300,820],[2840,720],[3300,760]].forEach(([x,y],i)=>addScene(i%4===0?'thorn':i%3===0?'rock':'palm',x,y,i%3===0?125:155));
const houses=[[2480,480,250],[2770,470,245],[3060,500,255],[2630,700,250],[2940,710,245]];houses.forEach(([x,y,w])=>{addScene('tent',x,y,w,1);addWall(x-w*.28,y-w*.18,w*.56,w*.23)});addScene('gate',2760,905,360,2);addScene('altar',1760,645,170,2);
[[1160,930],[1460,1040],[1980,1000],[2220,670],[1510,530]].forEach(([x,y],i)=>stones.push({id:i,x,y,done:false}));
const fs=[['sarai',300,1860,76],['lot',250,1905,76],['servant',205,1840,72],['girl',170,1900,68],['camel',110,1840,92],['sheep',70,1920,70]];followers=fs.map(([kind,x,y,w])=>({kind,x,y,w,dir:'up'}));updateHUD();updateGoals();}
function viewW(){return vw/zoom}function viewH(){return vh/zoom}
function setZoom(v,announce=true){zoom=Math.max(MIN_ZOOM,Math.min(MAX_ZOOM,Math.round(v*10)/10));zoomLevelEl.textContent=Math.round(zoom*100)+'%';const w=viewW(),h=viewH();cam.x=Math.max(0,Math.min(Math.max(0,world.w-w),player.x-w/2));cam.y=Math.max(0,Math.min(Math.max(0,world.h-h),player.y-h/2));if(announce)showToast(`Zoom ${Math.round(zoom*100)}%`,700)}
function progressPct(){let n=0;if(state.shechem)n++;if(state.moreh)n++;if(state.promise)n++;n+=state.stones/5;if(state.built)n++;return Math.round(n/5*100)}
function currentObjective(){if(!state.shechem)return'Travel north to Shechem';if(!state.moreh)return'Find the plain of Moreh west of Shechem';if(!state.promise)return'Approach the oak at Moreh';if(state.stones<5)return`Gather altar stones (${state.stones}/5)`;if(!state.built)return'Return to Moreh and build the altar';return'Mission complete'}
function updateHUD(){objectiveEl.textContent=currentObjective();progressEl.textContent=`Mission progress: ${progressPct()}%`;stonesEl.textContent=state.stones}
function updateGoals(){const vals=[state.shechem,state.moreh,state.promise,state.stones>=5,state.built];vals.forEach((done,i)=>{const el=document.getElementById('goal'+(i+1));el.classList.toggle('done',done);el.classList.toggle('active',!done&&(i===0||vals.slice(0,i).every(Boolean)));el.querySelector('span').textContent=done?'✓':'○'})}
function showToast(t,ms=1700){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),ms)}
function blocked(nx,ny){if(nx<55||ny<140||nx>world.w-55||ny>world.h-55)return true;for(const r of walls){if(nx+player.r>r.x&&nx-player.r<r.x+r.w&&ny+player.r>r.y&&ny-player.r<r.y+r.h)return true}return false}
function dist(x,y){return Math.hypot(player.x-x,player.y-y)}
function nearStone(){let best=null,bd=115;for(const s of stones){if(s.done)continue;const d=dist(s.x,s.y);if(d<bd){bd=d;best=s}}return best}
function atMoreh(){return dist(1760,610)<165}
function atShechem(){return player.x>2420&&player.x<3170&&player.y>340&&player.y<1020}
function drawOak(x,y,scale=1){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.fillStyle='#5f3d22';ctx.beginPath();ctx.moveTo(-34,32);ctx.bezierCurveTo(-48,-38,-27,-112,-4,-150);ctx.bezierCurveTo(8,-92,25,-45,36,32);ctx.closePath();ctx.fill();ctx.strokeStyle='#3e2b1d';ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-5,-100);ctx.lineTo(-80,-162);ctx.moveTo(8,-110);ctx.lineTo(88,-170);ctx.moveTo(-3,-128);ctx.lineTo(-35,-208);ctx.stroke();const blobs=[[-82,-175,70,50],[-30,-205,78,56],[36,-203,82,58],[92,-170,68,48],[-40,-150,92,58],[45,-145,95,58]];for(const [bx,by,rx,ry] of blobs){const g=ctx.createRadialGradient(bx-12,by-15,10,bx,by,rx);g.addColorStop(0,'#728b44');g.addColorStop(.55,'#4d7036');g.addColorStop(1,'#31512c');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(bx,by,rx,ry,0,0,Math.PI*2);ctx.fill()}ctx.restore()}
function interact(){if(!running||paused||state.complete)return;const s=nearStone();if(s&&state.promise){s.done=true;state.stones++;showToast(`Altar stone gathered — ${state.stones}/5.`);updateHUD();updateGoals();return}if(atMoreh()){if(!state.moreh){state.moreh=true;showToast('You found the plain of Moreh at Shechem.',1900);updateHUD();updateGoals();return}if(!state.promise){state.promise=true;paused=true;scripture.classList.add('visible');updateHUD();updateGoals();return}if(state.stones<5){showToast(`You still need ${5-state.stones} altar stone${5-state.stones===1?'':'s'}.`,1400);return}if(!state.built){state.built=true;state.complete=true;updateHUD();updateGoals();showToast('Abram built an altar unto the LORD.',1200);setTimeout(()=>{paused=true;complete.classList.add('visible')},850);return}}showToast('Nothing to interact with here.',700)}
function update(dt){if(!running||paused)return;let dx=0,dy=0;if(keys.has('KeyW')||keys.has('ArrowUp')||touchDirs.has('up'))dy--;if(keys.has('KeyS')||keys.has('ArrowDown')||touchDirs.has('down'))dy++;if(keys.has('KeyA')||keys.has('ArrowLeft')||touchDirs.has('left'))dx--;if(keys.has('KeyD')||keys.has('ArrowRight')||touchDirs.has('right'))dx++;player.moving=!!(dx||dy);if(player.moving){const l=Math.hypot(dx,dy);dx/=l;dy/=l;if(Math.abs(dx)>Math.abs(dy))player.dir=dx<0?'left':'right';else player.dir=dy<0?'up':'down';const step=player.speed*dt,nx=player.x+dx*step,ny=player.y+dy*step;if(!blocked(nx,player.y))player.x=nx;if(!blocked(player.x,ny))player.y=ny;player.anim+=dt*7;trail.unshift({x:player.x,y:player.y,dir:player.dir});if(trail.length>500)trail.length=500}else player.anim=0;followers.forEach((f,i)=>{const t=trail[Math.min(trail.length-1,28+i*16)];if(!t)return;const k=Math.min(1,dt*4.8);f.x+=(t.x-f.x)*k;f.y+=(t.y-f.y)*k;f.dir=t.dir});if(!state.shechem&&atShechem()){state.shechem=true;showToast('Shechem reached. Find the plain of Moreh.',2200);updateHUD();updateGoals()}const w=viewW(),h=viewH(),tx=player.x-w/2,ty=player.y-h/2;cam.x+=(tx-cam.x)*Math.min(1,dt*6);cam.y+=(ty-cam.y)*Math.min(1,dt*6);cam.x=Math.max(0,Math.min(Math.max(0,world.w-w),cam.x));cam.y=Math.max(0,Math.min(Math.max(0,world.h-h),cam.y))}
function drawGround(){ctx.fillStyle='#b9a15d';ctx.fillRect(0,0,viewW(),viewH());ctx.save();ctx.translate(-cam.x,-cam.y);const g=ctx.createLinearGradient(0,0,0,world.h);g.addColorStop(0,'#779454');g.addColorStop(.45,'#a6aa61');g.addColorStop(1,'#c9a965');ctx.fillStyle=g;ctx.fillRect(0,0,world.w,world.h);ctx.fillStyle='rgba(158,112,55,.28)';ctx.beginPath();ctx.moveTo(300,1950);ctx.bezierCurveTo(640,1650,1020,1480,1410,1290);ctx.bezierCurveTo(1800,1100,2240,930,2760,840);ctx.lineWidth=240;ctx.strokeStyle='rgba(210,174,103,.60)';ctx.lineCap='round';ctx.stroke();ctx.restore()}
function drawWorld(){ctx.save();ctx.scale(zoom,zoom);drawGround();ctx.save();ctx.translate(-cam.x,-cam.y);ctx.fillStyle='rgba(103,79,45,.13)';ctx.beginPath();ctx.ellipse(2780,570,620,400,0,0,Math.PI*2);ctx.fill();const list=[];scene.forEach(s=>list.push({type:'scene',y:s.y,o:s}));stones.forEach(s=>{if(!s.done)list.push({type:'stone',y:s.y,o:s})});followers.forEach(f=>list.push({type:'follow',y:f.y,o:f}));list.push({type:'player',y:player.y,o:player});list.sort((a,b)=>a.y-b.y);for(const d of list){if(d.type==='scene'){const s=d.o;if(s.img==='altar'&&!state.promise)continue;if(s.img==='altar'&&state.promise&&!state.built){sprite('altar',s.x,s.y,s.w,.25);continue}sprite(s.img,s.x,s.y,s.w,1,s.flip)}else if(d.type==='stone'){const s=d.o;ctx.save();ctx.strokeStyle='rgba(255,224,113,.9)';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(s.x,s.y+10,48,18,0,0,Math.PI*2);ctx.stroke();ctx.restore();sprite('rock',s.x,s.y,82)}else if(d.type==='follow'){const f=d.o;sprite(f.kind,f.x,f.y,f.w,.95)}else{let sp='abramFront',flip=false;if(player.dir==='up')sp='abramBack';else if(player.dir==='left'||player.dir==='right'){const arr=['abramRight1','abramRight2','abramRight3','abramRight4'];sp=arr[Math.floor(player.anim)%arr.length];flip=player.dir==='left'}sprite(sp,player.x,player.y,112,1,flip)}}drawOak(1760,610,1.32);if(state.moreh&&!state.promise){const glow=ctx.createRadialGradient(1760,520,10,1760,520,230);glow.addColorStop(0,'rgba(255,238,145,.46)');glow.addColorStop(1,'rgba(255,238,145,0)');ctx.fillStyle=glow;ctx.fillRect(1500,300,520,520)}if(state.promise&&!state.built){ctx.save();ctx.strokeStyle='#ffe596';ctx.lineWidth=3;ctx.setLineDash([9,8]);ctx.beginPath();ctx.arc(1760,635,110,0,Math.PI*2);ctx.stroke();ctx.restore()}const s=nearStone();if(s&&state.promise)drawPrompt('PICK UP STONE',s.x,s.y-95);else if(atMoreh())drawPrompt(!state.moreh?'DISCOVER MOREH':!state.promise?'HEAR THE PROMISE':state.stones<5?'GATHER 5 STONES':'BUILD THE ALTAR',1760,360);ctx.restore();ctx.restore()}
function drawPrompt(text,x,y){ctx.save();ctx.font='900 14px system-ui';ctx.textAlign='center';const w=ctx.measureText(text).width+26;ctx.fillStyle='rgba(28,19,10,.9)';ctx.strokeStyle='#f0c668';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(x-w/2,y,w,31,10);ctx.fill();ctx.stroke();ctx.fillStyle='#fff2c7';ctx.fillText(text,x,y+20);ctx.restore()}
function render(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,vw,vh);drawWorld()}function loop(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}
function resize(){dpr=Math.min(2,window.devicePixelRatio||1);vw=Math.max(320,shell.clientWidth);vh=Math.max(320,shell.clientHeight);canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);canvas.style.width=vw+'px';canvas.style.height=vh+'px';setZoom(zoom,false)}function reset(){complete.classList.remove('visible');pause.classList.remove('visible');scripture.classList.remove('visible');buildWorld();setZoom(1,false);running=true;paused=false;last=performance.now();showToast('Travel north through Canaan to Shechem.',1900)}
window.addEventListener('resize',resize,{passive:true});window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Space'||e.code==='Enter'){if(!e.repeat)interact();return}if(e.code==='Equal'||e.code==='NumpadAdd'){setZoom(zoom+ZOOM_STEP);return}if(e.code==='Minus'||e.code==='NumpadSubtract'){setZoom(zoom-ZOOM_STEP);return}if(e.code==='Escape'&&running&&!state.complete){paused=!paused;pause.classList.toggle('visible',paused);return}keys.add(e.code)});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();touchDirs.clear()});
document.querySelectorAll('.dir').forEach(btn=>{const dir=btn.dataset.dir;const down=e=>{e.preventDefault();touchDirs.add(dir);btn.classList.add('active');try{btn.setPointerCapture(e.pointerId)}catch{}};const up=e=>{e.preventDefault();touchDirs.delete(dir);btn.classList.remove('active')};btn.addEventListener('pointerdown',down);btn.addEventListener('pointerup',up);btn.addEventListener('pointercancel',up);btn.addEventListener('lostpointercapture',up)});
interactBtn.addEventListener('pointerdown',e=>{e.preventDefault();interact()});zoomInBtn.addEventListener('click',()=>setZoom(zoom+ZOOM_STEP));zoomOutBtn.addEventListener('click',()=>setZoom(zoom-ZOOM_STEP));menuBtn.addEventListener('click',()=>{if(running&&!state.complete){paused=true;pause.classList.add('visible')}});resumeBtn.addEventListener('click',()=>{paused=false;pause.classList.remove('visible');last=performance.now()});restartBtn.addEventListener('click',reset);againBtn.addEventListener('click',reset);continueBtn.addEventListener('click',()=>{scripture.classList.remove('visible');paused=false;last=performance.now();showToast('Gather five stones for the altar.',1800)});
resize();buildWorld();loadAtlas().then(()=>{loading.classList.remove('visible');running=true;paused=false;last=performance.now();showToast('Travel north through Canaan to Shechem.',1900)});requestAnimationFrame(loop);
})();
